### ISSUE TITLE
Unable to find a constructor to use for type System.DirectoryServices.SearchResult. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute.

### ISSUE THREAD

**Issue by DSBloom** [Azure/durabletask#1002]
I have a TaskActivity that returns an object of type `MySearchResult`, that in turn has a property of type `List<System.DirectoryServices.SearchResult>`. The problem is that `SearchResult` doesn't have a public parameterless constructor, and so Newtonsoft fails to serialize it.

The following code throws a Newtonsoft exception:

```
   var gatherResults =new List<MySearchResult>();
   Task<MySearchResult> getusersTask = context.ScheduleTask<MySearchResult>(typeof(GetADObjectsTask), ADObjectType.User);
   gatherResults.Add(await getusersTask);
```

How can I work around this issue?

**Comment by jviau** [comment]
This is a general serialization issue not specific to DurableTask. You will need to either:

1. Add custom JSON converter(s) for your type to Newtonsoft.Json
2. Create a DTO (data transfer object) which is serializable and converts to/from the type you want.

**Comment by jviau** [comment]
Closing as this is not Durable specific. See https://www.newtonsoft.com/json for more newtonsoft json information.
