### ISSUE TITLE
Poor code quality

### ISSUE THREAD

**Issue by andrew-kuzovov** [Azure/durabletask#1038]
After a glance at the code I see there a lot of code issues, for example:

1. Type [DispatchQueue](https://github.com/Azure/durabletask/blob/ee0861345763b8a6f5bdc433dc9be3938af3b0cd/src/DurableTask.AzureStorage/DispatchQueue.cs) has no (reasonable) usage
2. [AzureStorageOrchestrationService](https://github.com/Azure/durabletask/blob/ee0861345763b8a6f5bdc433dc9be3938af3b0cd/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs) - unused members: `EmptyHistoryEventList`, `leaseManager`, `hubCreationLock`
3. no consistent codestyle across repository

are there plans to maintain code clean?

**Comment by jviau** [comment]
Closing as not a productive issue
