### ISSUE TITLE
the await Task.Delay will make the ScheduleTask not execute in the second time and hang?

### ISSUE THREAD

**Issue by AiHaibara** [Azure/durabletask#1056]
```
while (status != "succeeded")
{
    status = await context.ScheduleTask<string>(typeof(CheckTaskStatusActivity), taskId);
    if (status != "succeeded")
    {
        await Task.Delay(3000);
        //Thread.Sleep(3000);
    }
}
```

Thread.Sleep(3000); will working normally, but await Task.Delay(3000); will make it hang.

**Comment by cgillum** [comment]
This is expected. Awaiting a non-durable task will cause your orchestration to hang. You should instead use `await context.CreateTimer(…)`. Check the wiki for more information and examples.

**Comment by AiHaibara** [comment]
> This is expected. Awaiting a non-durable task will cause your orchestration to hang. You should instead use `await context.CreateTimer(…)`. Check the wiki for more information and examples.

Ok, Thanks for share this.
