### ISSUE TITLE
Do you have any plans to support DSL?

### ISSUE THREAD

**Issue by fanslead** [Azure/durabletask#1072]

**Comment by cgillum** [comment]
No plans to support DSLs. One of the key features of DTFx is writing reliable workflows using general purpose programming languages, like C#.

That said, some teams have built their own DSLs in JSON or YAML, and then used DTFx to build an interpreter for the DSL. So while DTFx doesn't directly support DSLs, it does enable others to build DSLs. Hopefully we can provide some samples of this at some point.
