### ISSUE TITLE
Getting DurableTask.Core.Exceptions.TypeMissingException for all the Orchestrator/Activities

### ISSUE THREAD

**Issue by Man2MSFT** [Azure/durabletask#1078]
**Usage flow**: Service -> Our common package -> DTF

Scenario: We have created a Wrapper on top of DTF library and added a common functionality which can be use by our different partners, and on our side of package we are initializing orchestrators/activities as shown below (we follow the approach mentioned here [Link](https://andrewstevens.dev/posts/dependency-injection-durable-task/)):
```
ServiceCollection collection = new ServiceCollection;
collection.AddTransient<ControlFlowOrchestrator>();

var serviceProvider = collection.BuildServiceProvider();
taskHubWorker.AddTaskOrchestrations(new ServiceProviderObjectCreator<TaskOrchestration>(typeof(**ControlFlowOrchestrator**), serviceProvider));
```

we are facing an issue where we are getting the error while executing the callback, DTF is not able to find the orchestrator.

\<Task ID\>: Executing 'PackageName.DurableTask.Orchestrators.ControlFlowOrchestrator' orchestration logic
TaskOrchestrationDispatcher-8b76bd8f033b4b289a839c667fb7c8a3-0: Unhandled exception with work item '\<Task ID\>': **DurableTask.Core.Exceptions.TypeMissingException: Orchestration not found**: (**PackageName.DurableTask.Orchestrators.ControlFlowOrchestrator**, )
   at DurableTask.Core.TaskOrchestrationDispatcher.<ExecuteOrchestrationAsync>d__22.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 478

**note**: When we are trying to register the Orchestrator with default constructors without ServiceCollection, it is working fine and able to resolve the Type.
```
taskHubWorker.AddTaskOrchestrations(typeof(ControlFlowOrchestrator))
```

While using dependency injection with ServiceProviderObjectCreator we are not able resolve registered Types. Please help us to resolve this issue.

**Comment by Man2MSFT** [comment]
@cgillum can you please help us here?

**Comment by cgillum** [comment]
This sounds like an issue with the `ServiceProviderObjectCreator` you are using. I suggest following up with the owner of that as I'm not aware of how it works.

**Comment by Man2MSFT** [comment]
@cgillum Okay, thank you.

We have tried few things and it's working now.
Closing this ticket.
