### ISSUE TITLE
ETA for new .Net Core Nuget package?

### ISSUE THREAD

**Issue by danieltremblay** [Azure/durabletask#130]
In the readme it mentions that PR  https://github.com/Azure/durabletask/pull/104 has been merged and that a new 2.x.x Nuget package will be made available. Any idea when this will happen?

**Comment by simonporter** [comment]
The readme has been updated, the packages are available here:
https://www.nuget.org/packages/DurableTask.Core
https://www.nuget.org/packages/DurableTask.ServiceBus
https://www.nuget.org/packages/DurableTask.Emulator
https://www.nuget.org/packages/DurableTask.AzureStorage
