### ISSUE TITLE
TaskHubClient.CreateOrchestrationInstanceAsync() called within an orchestration seems to hang

### ISSUE THREAD

**Issue by poveilleux** [Azure/durabletask#131]
Hi,

So, I'll explain my scenario. I have an orchestration (let's call it `ValidationOrchestration`) that does some validations based on an event received on the service bus (my application sends a request event on the service bus for another application and is expecting a response at some point in time). If the validations pass, I create another type of orchestration (let's call it `ProcessingOrchestration`) using `TaskClient.CreateOrchestrationInstanceAsync()`. I am doing this because I want to seperate the validation code from the processing code. I thought it would work but it seems that the `ValidationOrchestration` instance is waiting on the `ProcessingOrchestration` it started to complete. I would be expecting this behaviour with `CreateSubOrchestrationInstance`. I want the `ValidationOrchestration` to start the `ProcessingOrchestration` and then complete. Did I do it right?

Thank you

**Comment by cgillum** [comment]
Can you share some code which illustrates what you're trying to do?

**Comment by poveilleux** [comment]
I simplified my code to the simplest possible. I think it explains what I want to do.
```cs
public class ValidationOrchestration : TaskOrchestration<string, ValidationInput, object, string>
{
    private readonly TaskCompletionSource<GetInfoResponseEvent> m_responseHandle;
    
    public sealed override void OnEvent(OrchestrationContext context, string eventName, object input)
    {
        if (input is GetInfoResponseEvent typedInput)
        {
            m_responseHandle.SetResult(typedInput);
        }
    }
    
    public override async Task<string> RunTask(OrchestrationContext context, ValidationInput input)
    {
        await context.ScheduleTask<bool>(typeof(SendEventActivity), new SendEventActivityInput
        {
            Event = new GetInfoRequestEvent
            {
                DurableInstanceId = context.OrchestrationInstance.InstanceId,
                UniqueId = input.UniqueId
            }
        });

        // A RaiseEvent is done outside the orchestration to set this TaskCompletionSource with the OnEvent() method.
        GetInfoResponseEvent getResponseEvent = await m_responseHandle.Task;

        var notificationEvent = Mapper.Map<NotificationEvent>(input);
        var startProcessingOrchestration = false;

        var validationPasses = PerformValidations(getResponseEvent);
        if (validationPasses)
        {
            startProcessingOrchestration = true;
            notificationEvent.ResponseCode = "Started";
        }
        else
        {
            notificationEvent.ResponseCode = "Error";
        }

        if (startProcessingOrchestration)
        {
            var processingOrchestrationInput = Mapper.Map<ProcessingOrchestrationInput>(input);
            // I thought it would just create the new Orchestration and finish executing this one, but it doesn't...
            await OrchestrationHelper.CreateOrchestrationInstanceAsync<ProcessingOrchestration>(processingOrchestrationInput);
        }

        await context.ScheduleTask<bool>(typeof(SendEventActivity), new SendEventActivityInput
        {
            Event = notificationEvent
        });

        return null;
    }
}
```

**Comment by cgillum** [comment]
Thanks. I suspect the problem is this line:

```csharp
await taskHubClient.CreateOrchestrationInstanceAsync(typeof(ProcessingOrchestration), processingOrches
```

An orchestration is only allowed to await on durable tasks created by the `OrchestrationContext` object. In your case, you're awaiting on a task from `TaskHubClient`, which is non-durable. This confuses the framework and causes the orchestration to stall.

To fix this, you can wrap the `TaskHubClient` call inside a new activity function.

**Comment by poveilleux** [comment]
It makes perfect sense. I will do that and let you know. Thank you.

**Comment by poveilleux** [comment]
With what you are saying, I should not be able to await on the TaskCompletionSource, but this works just fine. How is that possible?

**Comment by cgillum** [comment]
Yes, my explanation was too simplistic. I'll try to explain further.

The way the durable task framework is implemented, all orchestration code must execute on a thread controlled by the orchestration dispatcher. When you call `TaskHubClient.CreateOrchestrationInstanceAsync`, the callback is executed on a worker pool thread. The orchestration dispatcher doesn't know anything about this new worker pool thread and therefore isn't able to properly resume execution.

In the case of your `TaskCompletionSource`, when you call `SetResult`, the completion runs on the same thread as `OnEvent`, thus the orchestration engine is able to execute just fine (note that behind the scenes, all async APIs in `OrchestrationContext` are implemented using `TaskCompletionSource`).

**Comment by poveilleux** [comment]
It is clearer now. Thanks a lot for the detailed explaination.

**Comment by poveilleux** [comment]
@cgillum So, to give you a feedback, I used a `TaskActivity` to wrap my call to `CreateOrchestrationInstanceAsync()` as you suggested and it worked. Thanks again for your help.
