### ISSUE TITLE
ExecutionId vs InstanceId: what is the difference?

### ISSUE THREAD

**Issue by poveilleux** [Azure/durabletask#136]
Hi,

In my implementation using DurableTasks, I am sometimes waiting on an external service to do something and I am sending the InstanceId to that service so when it is done it can tell me which orchestration instance to "wake up". I just wanted to know the difference between the InstanceId and ExecutionId to make sure I understood orchestrations correctly.

Thank you

**Comment by simonporter** [comment]
InstanceId refernces your orchestration, the ExecutionId refers to a specific instance, in the case of using ContinueAsNew a single InstanceId will have multiple ExecutionIds, only one can be active at any point in time.

**Comment by poveilleux** [comment]
That's exactly what I wanted to hear. Thank you Simon!
