### ISSUE TITLE
Parallel initialization of two instances may fail.

### ISSUE THREAD

**Issue by mtuchkov** [Azure/durabletask#14]
The remote server returned an error: (409) Conflict. SubCode=40901. Another conflicting operation is in progress

The issue happens when more than two instances are initializing simultaneously. Both run CreateOrUpdateQueue and then one of them is getting 409.

**Comment by cgillum** [comment]
Closing out old issues - not sure if this is still an issue in the latest code or not, but much has changed so ideally we'd collect a newer repro of this if it's still an issue.
