### ISSUE TITLE
The AzureStorageOrchestrationService in DurableTask.AzureStorage does not support IOrchestrationServiceInstanceStore

### ISSUE THREAD

**Issue by adarsh1** [Azure/durabletask#149]
The AzureStorageOrchestrationService does not provide the option to Inject an !OrchestrationInstanceServiceStore and does not use this object internally. As a result it does not maintain  feature parity with the ServiceBusOrchestrationService

**Comment by cgillum** [comment]
This was fixed as part of this PR: https://github.com/Azure/durabletask/pull/150
