### ISSUE TITLE
VS2017 Azure Functions Template Incompatible

### ISSUE THREAD

**Issue by adamreed90** [Azure/durabletask#156]
The template included in Visual Studio 2017 for an Azure Function creates a .NET Standard 2.0 based project, which will not allow you to install the package. 

`PM> Install-Package Microsoft.Azure.WebJobs.Extensions.DurableTask
Install-Package : Unable to find package 'Microsoft.Azure.WebJobs.Extensions.DurableTask'
At line:1 char:1
+ Install-Package Microsoft.Azure.WebJobs.Extensions.DurableTask
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:00.1769051`

**Comment by cgillum** [comment]
The correct repo for **Microsoft.Azure.WebJobs.Extensions.DurableTask** is https://github.com/Azure/azure-functions-durable-extension. Can you please open an issue there?
