### ISSUE TITLE
TypeLoadException  when using DurableTask.Core 2.0.0.5 

### ISSUE THREAD

**Issue by rcoccia** [Azure/durabletask#178]
Hi,
we're experimenting a TypeLoadException  when using DurableTask.Core 2.0.0.5 
```
System.TypeLoadException: Could not load type 'Newtonsoft.Json.SerializationBinder' from assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
   at DurableTask.Core.Serializing.PackageUpgradeSerializationBinder.BindToName(Type serializedType, String& assemblyName, String& typeName)
```

It seems that DurableTask.Core  has a strong dependency on Newtonsoft.Json.SerializationBinder. 
Newtonsoft.Json.SerializationBinder was available (but deprecated) since version 10.0.3 of Newtonsoft.Json 
Newtonsoft.Json.SerializationBinder  is no more available from version >11
Any suggestion, unfortunatelly downgrade Newtonsoft.Json to version 10.0.0.3 is not feasible in our case
thanks

**Comment by simonporter** [comment]
This should be resolved, please reopen if its not
