### ISSUE TITLE
"Duplicate start event.." gets logged erroneously every time ContinueAsNew() is called

### ISSUE THREAD

**Issue by affandar** [Azure/durabletask#19]
For ContinueAsNew() we emit an ExecutionStartedEvent but also create the new state (with this event already populated in the execution history).

When this event is received, the taskorchestrationdispatcher looks at the current state, finds the execution started event already there and then finds the actual message which also contains an execution started event and ignores the message after tracing the duplicate started event message.

To fix this we can either add a switch on the state itself to indicate whether it was a genuine dupe or whether it was a dupe because of the way we are doing continueasnew. We can also fix continueasnew to not create the state, however that would be a much trickier change at this point.

**Comment by cgillum** [comment]
Closing out old issues - we definitely aren't seeing this issue today, so likely already fixed.
