### ISSUE TITLE
Open source the Azure Service Fabric Reliable Collections Provider

### ISSUE THREAD

**Issue by MedAnd** [Azure/durabletask#218]
Azure Event Hubs run on top of Azure Service Fabric, and I believe they use this framework for workflow functionality as per: [Cesar Ruiz-Meraz: Azure Event Hubs](https://youtu.be/OxXGnbHAXB0)  

Consider open sourcing the Azure Service Fabric Reliable Collections Provider.

**Comment by simonporter** [comment]
This is in plan, the code is currently under review: #210

**Comment by MedAnd** [comment]
Been a while @simonporter... any update?

**Comment by msfussell** [comment]
See this PR https://github.com/Azure/durabletask/pull/307

**Comment by MedAnd** [comment]
Closing as the [DurableTask.AzureServiceFabric](https://github.com/Azure/durabletask/tree/master/src/DurableTask.AzureServiceFabric) is now in master!
