### ISSUE TITLE
Unable to set OrchestrationInstance and IsReplaying on OrchestrationContext from implementation

### ISSUE THREAD

**Issue by lukak-msft** [Azure/durabletask#236]
I was trying to unit test some of the code I wrote using orchestrations, and I thought the easiest way would be to implement [OrchestrationContext ](https://github.com/Azure/durabletask/blob/f9cc450539b5e37c97c19ae393d5bb1564fda7a8/src/DurableTask.Core/OrchestrationContext.cs) class since it's abstract, and pass it to the orchestration and validate the behavior.
Unfortunately `IsReplaying` and `OrchestrationInstance` properties are non-virtual, and do not expose a protected setter.

**Comment by cgillum** [comment]
This will go out with the v2.1.0 release
