### ISSUE TITLE
Build errors.  Cant find files. SourceLink problem?

### ISSUE THREAD

**Issue by georgestevens99** [Azure/durabletask#240]
I both cloned this repo, and also made a zip file and unzipped it, both on my dev system.  In both directories:  Opened the solution in VS 2017 OK.  All nuget packages were restored.  Hit build and in all cases got numerous cannot find file or directory errors.  Investigated on web and it seemed it may involve SourceLink, of which there seem to be a couple version.

I am doing a quick and dirty exploratory assessment of this technology and I'd like a quick way to get it up and running to do that without having to spend a lot of time hooking up a bunch of stuff.  Kind a disappointed it didn't build right off the bat, and make things really, really easy to assess!

Can you suggest a way I can quickly get to working with exploratory coding and get rid of the build errors.  I can be more specific about the errors if you wish.
Thanks, George

**Comment by georgestevens99** [comment]
PS VS2017 is 15.6.4

**Comment by georgestevens99** [comment]
Oops.  Closed by mistake.  This issue is still open.

**Comment by cgillum** [comment]
@georgestevens99 do you need to be able to build from source, or are you able to use the pre-built nuget packages?

* https://www.nuget.org/packages/Microsoft.Azure.DurableTask.ServiceBus
* https://www.nuget.org/packages/Microsoft.Azure.DurableTask.Emulator
* https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage

As far as building from source, I haven't seen any such issues. The VSTS/Azure DevOps server is able to build it fine with the latest dotnet toolset. For local builds, I'm currently using VS2017 15.9.4. There is a note in the [SourceLink repo](https://github.com/dotnet/sourcelink/blob/master/README.md) which talks about certain requirements, which might apply to your situation:

> Note that .NET Core SDK 2.1.300 or newer is required for SourceLink to work. If building via desktop msbuild (as opposed to dotnet build) you'll need version 15.7.

So it sounds like you'll need to upgrade to VS2017 15.7 or greater.

**Comment by georgestevens99** [comment]
Hi Chris,
Thanks for the most helpful information.  I upgraded to VS 2017 1.9.4 and
build OK with no other changes

Thanks,
George

**Comment by georgestevens99** [comment]
Follow the instructions in cgillum's post above.  The problem was an out of date version on Visual Studio, i.e. 15.6.4 and not with any of the material in this repo.
