### ISSUE TITLE
AzureStorageOrchestrationService TokenProvider/MSI support

### ISSUE THREAD

**Issue by daksha121** [Azure/durabletask#243]
We plan to use Managed Identity in our project to access Azure Storage (https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-vm-windows-access-storage#get-an-access-token-and-use-it-to-call-azure-storage) . Are there any plans to support a TokenProvider way to use AzureStorageOrchestrationService instead of using a storage connection string?

**Comment by cgillum** [comment]
No plans currently, but we could certainly look into this as a very good feature request, or accept it as a PR.

**Comment by cgillum** [comment]
This will go out with the v1.5.0 release.
