### ISSUE TITLE
Durable Redis Provider

### ISSUE THREAD

**Issue by cgillum** [Azure/durabletask#253]
### Overview
The Durable Task Framework today only supports Azure-hosted backends. Service Bus and Azure Storage are the current "GA" provider and there is a Service Fabric provider in the works. However, there are a set of developers [who want or need a non-Azure provider](https://github.com/Azure/durabletask/issues/102) whose backend can be hosted in an on-premises environment. A [Redis](https://redis.io/) provider could help meet this need for on-premises data storage, while also supporting Azure deployments via the [Azure Redis Service](https://azure.microsoft.com/en-us/services/cache/).

This issue tracks building a durable, high-performance Redis provider which can be used in both Azure environments and on-premises deployments.

### Support Checklist
- [x] Local development / testing instructions for Windows 10 ([WSL](https://medium.com/@RedisLabs/windows-subsystem-for-linux-wsl-10e3ca4d434e)) and macOS environments
- [x] Support for .NET Core (support for .NET Framework is nice to have but not required)
- [ ] Support for [Docker containers](https://www.docker.com/resources/what-container)
- [ ] Works with local [Redis clusters](https://redis.io/topics/cluster-tutorial) and the [Azure Cache for Redis](https://azure.microsoft.com/en-us/services/cache/) service
- [ ] Detailed ETW telemetry (required for [Durable Functions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview) support)
- [ ] Durable [persistence](https://redis.io/topics/persistence)
- [ ] Performance on-par with or better than Service Bus and Azure Storage providers

### Feature Checklist
- [x] Executing orchestrations and activities
- [ ] Timers
- [ ] External events
- [ ] Termination
- [ ] Single instance query
- [ ] Multi-instance query
- [ ] Task hubs

### Resources
* [Task queues (FIFO and delayed) | Redis in Action](https://redislabs.com/ebook/part-2-core-concepts/chapter-6-application-components-in-redis/6-4-task-queues/)

### Design
Design details are TBD. We'll update this issue as time progresses.

**Comment by michaelringholm** [comment]
Hi Chris,

First of all, great stuff you are doing with Durable Functions.

We have several customers in the financial industry who can't run in a public cloud, but they really want to use Durable Functions on premises. The need for an Azure backed Storage Account is keeping them from moving in this direction. 

Any updates on this issue?

Let me know if I can help with anything.

**Comment by maskx** [comment]
Hi @michaelringholm,

For your information, I'm working on a [SQLServer Provider](https://github.com/maskx/DurableTask.SQLServer), and an [OrchestrationService](https://github.com/maskx/OrchestrationService).  these will support using DurableTask on premises

**Comment by oising** [comment]
@cgillum Does (will?) this support Durable Entities? I'm not interested in orchestrations/activites. I have no need for call, only signal.

**Comment by ConnorMcMahon** [comment]
This currently does NOT support Durable Entities at this time, and there are no immediate plans to add support for them.

**Comment by oising** [comment]
> This currently does NOT support Durable Entities at this time, and there are no immediate plans to add support for them.

Any hints where I should look to get an idea how to implement this part? I have no need of anything except this. I want to improve latency.
