### ISSUE TITLE
Failing EmulatorFunctionalTests

### ISSUE THREAD

**Issue by Preecington** [Azure/durabletask#255]
Whilst working on #203 I've noticed that the PR #251 has introduced failures into the `EmulatorFunctionalTests`, namely `MockGenerationTest` and `MockRecreateOrchestrationTest`.

This manifests as a timeout, but the underlying issue is the orchestration is continually retrying due to a corrupt state where there are Multiple ExecutionCompletedEvents in the history.

I managed to trace the issue down to something to do with the `OrchestrationRuntimeState` being passed in to `CompleteTaskOrchestrationWorkItemAsync` inside `DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync` ([Line #402](https://github.com/Azure/durabletask/blob/master/src/DurableTask.Core/TaskOrchestrationDispatcher.cs#L402)  on `master` as of this issue). Perhaps the local orchestration service wasn't properly updated to deal with the new raised event fix?

I won't have time to look at this for another few days, so I thought I'd just post my findings here.

**Comment by cgillum** [comment]
FYI @adarsh1
