### ISSUE TITLE
Equivalent of Durable​Orchestration​Context::WaitForExternalEvent to run human approval workflow?

### ISSUE THREAD

**Issue by maulik-modi** [Azure/durabletask#265]
We are evaluating if Durable task framework OnPremise, it can be used to run human approval workflow with Azure table storage, storage queues and service bus.

We found that there is  [WaitForExternalEvent](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationContextBase.html#Microsoft_Azure_WebJobs_DurableOrchestrationContextBase_WaitForExternalEvent_System_String_System_TimeSpan_) method in DurableOrchestrationContext. However, we could not find DurableOrchestrationContext class in Github repo. [Durable functions](https://markheath.net/post/durable-functions-wait-external-event-timeout) usage is explained in article.

Is there any plan to make this WaitForExternalEvent or equivalent functionality in DurableTask Github repository?

**Comment by kashimiz** [comment]
Hi @maulik-modi, I'm not aware of any plans to implement WaitForExternalEvent in Durable Task at this time. @cgillum for roadmap.

**Comment by cgillum** [comment]
It's possible to implement this pattern directly in the Durable Task Framework using the technique described in [this wiki page on external events](https://github.com/Azure/durabletask/wiki/Feature---Waiting-on-External-Events-%28Human-Interaction%29). Durable Functions simply wrapped this existing pattern in the `DurableOrchestrationContext` APIs.
