### ISSUE TITLE
100% CPU Utilization after some time

### ISSUE THREAD

**Issue by RobTF** [Azure/durabletask#271]
Hi,

There appears to be an issue whereby in some cases a durable function will cause the CPU of its host to spike to 100% and all durable functions stop. It almost feels like a tight loop in the durable task stuff as I can replicate it with functions that do no real work and non-durable functions still run despite the CPU being pegged at 100%.

I found this happening on Azure and downloaded a profiler session from the process that was encountering the issue. I have attached a screenshot showing that 97% of the CPU time was going on OrchestrationManager.GetNextSessionAsync, and running off into the Azure Storage stuff behind the scenes.

The durable function in question is an eternal orchestration, however changing this to a single-fire orchestration triggered by a timer gives the same result, so I don't think that makes a difference, but if there is some newbie mistake that can cause this please let me know.

If anyone would like the original .diagsession file I can supply this if it would be helpful.

regards,

Rob

![stack_trace](https://user-images.githubusercontent.com/4292237/54887589-e4d51c80-4e51-11e9-83df-370e2f330351.png)

<img width="995" alt="Screenshot 2019-03-24 at 16 35 05" src="https://user-images.githubusercontent.com/4292237/54887689-3205be00-4e53-11e9-9dad-49f1715cc95b.png">

**Comment by cgillum** [comment]
Thanks for sharing this. I would like to investigate further. Is there anything else you can tell us about in what situations you observed this?

Also, is there any unique identifier you can share to help us locate your repro in our Azure telemetry? For example, an instance ID or function execution ID from around the time you observed the high CPU? The region and approximate time in UTC would also be helpful.

Thanks!

**Comment by RobTF** [comment]
Hi Chris,

Thanks for the reply. I've been wracking my brains trying to think of what we might be doing that could be causing this behavior as we have successfully used durable functions in other, unrelated projects but so far I'm coming up blank. We have made some efforts to experiment with changes to our code (such as removing the eternal orchestration and replacing it with a timer) but it's difficult to test as we have observed the problem occuring randomly anywhere between 3 hours to 2 days. Once the issue starts the app service never recovers and will sit at 100% CPU and not fire a durable function again until the function app is restarted. I am uncertain as to whether it is possible to replicate the problem locally using the cli tools and Azure storage emulator, but we haven't yet managed to do so.

I'm more than happy to send anything you might find useful over (app service ID, function app name, application insights details, times/dates the problem has occurred etc.) but I'd rather do that on a PM or via e-mail if possible; is there anywhere I can send you the information?

If I can think of anything else or if any of our experiments yield useful information I will update this issue with our findings.

regards,

Rob

**Comment by cgillum** [comment]
I'm studying the code in question (which can be found [here](https://github.com/Azure/durabletask/blob/f91ae79a7b9c027084f57fbe291f8df72a7f717e/src/DurableTask.AzureStorage/OrchestrationSessionManager.cs#L295)). It seems that eternal orchestrations might be susceptible to this, though it would be ideal to have some repro data to look at.

If you could send me your function app name and a rough timestamp of when you observed this to {my github alias} + @microsoft.com, that would allow me to learn more about the conditions which may be triggering this behavior.

**Comment by RobTF** [comment]
Hi Chris,

Apologies for the delay, I was travelling with work. I've sent the requested information over.

regards,

Rob

**Comment by mpaul31** [comment]
We are experience the same however our service bus trigger seize as well. I've only noticed this once we put heavy load on calling StartNewInstance. I'll send you our info.

**Comment by mpaul31** [comment]
@RobTF whoch versions of the runtimes and durable are your working and non-working?

**Comment by mpaul31** [comment]
@cgillum I also sent you some information via e-mail.

**Comment by cgillum** [comment]
@RobTF and @mpaul31 thanks for your info and sorry for the delay. In both cases, I'm noticing repeated warnings from the DurableTask.AzureStorage ETW provider about out of order messages. This is not expected under normal circumstances and results in reprocessing of messages, so something seems to be going on here. I'll continue to look at these to see if I can link them to the high CPU usage.

@mpaul31 In your case, I also see some `NullReferenceExceptions` in the Durable Task extension. I think this might be a separate bug, but I'll investigate that as well.

**Comment by mpaul31** [comment]
thanks @cgillum for digging into this and the awesome framework! i’m a newbie to durable and really enjoying it thus far!
