### ISSUE TITLE
System.TypeLoadException when using DureableTask.Core 2.1.1 with DurableTask.ServiceBus 2.0.10

### ISSUE THREAD

**Issue by sufyannisar** [Azure/durabletask#286]
Hi,
We are getting this error when using DurableTask.Core 2.1.1 (latest) with DurableTask.ServiceBus 2.0.10 (latest):

> `An unhandled exception of type 'System.TypeLoadException' occurred in Unknown Module.
> Additional information: Method 'get_EventBehaviourForContinueAsNew' in type 'DurableTask.ServiceBus.ServiceBusOrchestrationService' from assembly 'DurableTask.ServiceBus, Version=2.0.10.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd' does not have an implementation.`

here is out sample test code:
```
var serviceBus = ConfigurationManager.AppSettings["OrderServiceBus"];
var orderStorageAccount = ConfigurationManager.AppSettings["OrderStorageAccount"];
var taskHubName = ConfigurationManager.AppSettings["TaskHubName"];

var instanceStoreStatic = new AzureTableInstanceStore(taskHubName,
    orderStorageAccount);

var blobStoreStatic = new AzureStorageBlobStore(taskHubName,
     orderStorageAccount);

var serviceSettingsStatic = new ServiceBusOrchestrationServiceSettings
{
    MessageCompressionSettings = new CompressionSettings
    {
        Style = CompressionStyle.Threshold,
        ThresholdInBytes = (150 * 1024) // Limit mention in dtf test-case: SessionExceededLimitNoCompressionTest
    }
};
IOrchestrationService orchestrationServiceAndClientStatic = new ServiceBusOrchestrationService(
    serviceBus, taskHubName, instanceStoreStatic,
    blobStoreStatic,
    serviceSettingsStatic);
```

**Comment by ltdavids** [comment]
Have you gotten past this?  I am having the same issue.

**Comment by sufyannisar** [comment]
Yeah. we have an internal nuget server, i just created a brand new version of all DurableTask.** nugets, from master branch, and published them here. Now we are using that.

**Comment by cgillum** [comment]
Sorry for the late response. It seems this fell through the cracks. I've just now uploaded an up-to-date version of DurableTask.ServiceBus to nuget.org here: 

https://www.nuget.org/packages/Microsoft.Azure.DurableTask.ServiceBus/2.1.1

(It might take a few minutes for it to be available)

**Comment by acrigney** [comment]
You need to update the nuget package reference as the new version is not found from VS2019
