### ISSUE TITLE
System.TypeLoadException: 'Method 'get_EventBehaviourForContinueAsNew'

### ISSUE THREAD

**Issue by ddobric** [Azure/durabletask#294]
Hi all,

getting following exception when starting the hub:

>System.TypeLoadException
  HResult=0x80131522
  Message=Method 'get_EventBehaviourForContinueAsNew' in type 'DurableTask.ServiceBus.ServiceBusOrchestrationService' from assembly 'DurableTask.ServiceBus, Version=2.0.10.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd' does not have an implementation.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

### Dependencies and Project file

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.DurableTask.AzureStorage" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.DurableTask.Core" Version="2.1.1" />
    <PackageReference Include="Microsoft.Azure.DurableTask.ServiceBus" Version="2.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedLib.NetCore\SharedLib.NetCore.csproj" />
  </ItemGroup>

</Project>
```

**Comment by cgillum** [comment]
You need to upgrade your `Microsoft.Azure.DurableTask.ServiceBus` reference to [2.1.1](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.ServiceBus/2.1.1).
