### ISSUE TITLE
Duplicate TaskScheduledIds and activity result deserialization

### ISSUE THREAD

**Issue by mark-r-cullen** [Azure/durabletask#296]
Could be caused by the way we were awaiting activities in the orchestrator - we are testing using suborchestrator to see if that solves the issue, but probably still wants some investigation and maybe even some kind of check and exception if possible, as it was quite hard to track down.

![durable function results](https://user-images.githubusercontent.com/12714684/58720630-a36d6a00-83ca-11e9-89b5-ba9a1ebe4696.png)

The issue can be seen in this screenshot. There are duplicate TaskScheduledIds (e.g 1151 - highlighted is the correct result, the other one is a different activity entirely) and the result logged against them are different. As in... it appears to have actually run two completely different activites under the same task id.

It seems like the orchestrator(?) was then picking up the "wrong" 1151 result. In this particular case it meant that the "assets" property on our deserialized object was null... i.e got the json with AssetId and AssetVersionId instead of the json with requestId and assets.

**Comment by cgillum** [comment]
Which version of the extension are you using? A fix was made in a recent release which does some de-duplication of event IDs: https://github.com/Azure/durabletask/pull/290

**Comment by cgillum** [comment]
Closing for now, but let us know if the [latest release](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage) does not resolve this issue for you.
