### ISSUE TITLE
Unable to implement Database Instance Store due to lack of documentation

### ISSUE THREAD

**Issue by cbrianball** [Azure/durabletask#308]
I'm trying to write a provider to store instance information in a database. I'm implementing the `IOrchestrationServiceInstanceStore`, but I can't seem to wrap my head around the meaning of `InstanceId`, `ExecutionId`, and `SequenceNumber`. I feel they are all important, but I don't understand what each one means exactly and how data should be persisted/retrieved. I've tried looking at the `AzureTableInstanceStore` implementation as a reference, but I haven't worked with Azure tables enough to really understand what is going on in that code.

Is there any sort of documentation/material that can help me understand exactly what each method of the `IOrchestrationServiceInstanceStore` interface is trying to accomplish and when it is invoked? What would be especially helpful is sample data that shows what the inputs and return values of the method looks like.

For instance, is SequenceNumber some sort of versioning value and should I keep a record of all of them or just the most recent one (e.g., if I have a table for the `OrchestrationStateInstanceEntity` class, should The PK be InstanceId and ExecutionId, or should SequenceNumber be part of the PK)?

The closest I've come is having my orchestrations execute succesfully, but then there's an infinite loop where my implementation's `GetOrchestrationHistoryEventsAsync` is called over and over (with a slight delay), asking for the same instanceId and executionId over and over like the framework believes the orchestration hasn't finished executing yet.

**Comment by cbrianball** [comment]
I've got mine implementation working, though I would still like to understand the significance of InstanceId vs ExecutionId. In all scenarios I've run so far, I have not seen an InstanceId with more than one ExecutionId (or vice versa).

Understanding the difference may help me write a better implementation. Thanks!

**Comment by ConnorMcMahon** [comment]
One example of an orchestration instance can have multiple execution ids is through the use of the `ContinueAsNew()` API. I can't think of any other way to have an instance id correspond to more than one ExecutionId or the top of my head,, but there may be other situations.
