### ISSUE TITLE
AzureTableInstanceStore can only be initialized once on .Net Core 3.0

### ISSUE THREAD

**Issue by scabana** [Azure/durabletask#319]
Exception: ```{"Cannot set initonly static field 'MinDateTime' after type 'DurableTask.Core.Common.DateTimeUtils' is initialized."}``` is thrown if ```new AzureTableInstanceStore``` is called more than once. Seems like the reflection call at https://github.com/Azure/durabletask/blob/f9cc450539b5e37c97c19ae393d5bb1564fda7a8/src/DurableTask.Core/Common/DateTimeUtils.cs#L41-L47 is not blocked in .net core 3.0 if ran more than once. Because of this, it's not possible to initialize more than 1 AzureTableInstanceStore instance per application lifetime.

For reference: https://github.com/dotnet/coreclr/issues/21268#issuecomment-442675193

**Comment by cgillum** [comment]
Interesting. So the reflection code works the first time but fails the second time?

Also, can you describe a scenario where you might have more than one `AzureTableInstanceStore` instance per application lifetime? I'm wondering whether this will impact Durable Functions after the Azure Functions host moves to .NET Core 3.

FYI @simonporter

**Comment by scabana** [comment]
That's the behavior I'm getting, fails on second attempt.

As for why, I don't know. I'm migrating a service using durable tasks, didn't write the original code (which may not be the most optimal). For the moment, transformed the ```AzureTableInstanceStore``` as a singleton.
