### ISSUE TITLE
Can the durable task framework generate a webhook callback url?

### ISSUE THREAD

**Issue by vkurpad** [Azure/durabletask#321]
I'm looking to use durable azure functions to work with a long running process that only supports webhook callbacks. Does the framework allow me generate a webhook callback that I can use within the same function execution context?

**Comment by cgillum** [comment]
The Durable Task Framework (DTFx) doesn't have any notion of webhooks. That said, you can certainly implement your own support for this by hosting DTFx in a web app and using the [external events](https://github.com/Azure/durabletask/wiki/Feature---Waiting-on-External-Events-%28Human-Interaction%29) pattern to route a webhook to a specific orchestration context.

[Durable Functions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview) (an Azure Functions-hosted wrapper around DTFx) on the other hand has first-class support for this scenario. See the [external events article](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-external-events) for more information.
