### ISSUE TITLE
SignalR with Sql Storage

### ISSUE THREAD

**Issue by ackava** [Azure/durabletask#340]
Sql Storage Support looks great, but it only offers storage.

If I create IOrchestrationServiceClient on SignalR and use Sql Server storage, do I have to make SignalR persistent?

Can task framework recover from Sql storage without SignalR being persistent, lets assume web app hosting SignalR is restarted, and worker is restarted, will it retain the state?

**Comment by cgillum** [comment]
We recently created a full SQL Server implementation. More details here: https://github.com/Azure/durabletask/issues/433#issuecomment-855013250.

If I understand the question correctly, client operations don't necessarily require persistent connections. The only requirement is that the orchestration runtime state is stored reliably (assuming you want durability for your orchestrations).
