### ISSUE TITLE
Using DI in TaskOrchestration or TaskActivity

### ISSUE THREAD

**Issue by xTeKillax** [Azure/durabletask#343]
Hello,
I'm struggling to get my DI working with DTF. Im running in a .NET Core 3 service worker while using Autofac for DI.
I register everything in an autofac module to use mediatr, i then do the DI via constructor but when testing, it seems like something break without any notice. The debugger is lost while executing ScheduleTask method.

I replaced the dll of DurableTask.Core with the debug version to get more information and I see this exception in the output :
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll

Am I missing something ?
Thank's you

**Comment by ConnorMcMahon** [comment]
Are you using the Azure Storage implementation? If so, there was this issue #319, though I believe it was addressed in the latest build.

**Comment by xTeKillax** [comment]
Thanks for the reply Connor !
The problem is different from the one you mentioned, it's really about injecting a dependency through constructor of a TaskActivity or a TaskOrchestration.
Everything work fine but as soon as i create my constructor with the DI, it fail silently without breaking on the code at any point.

I noticed  the problem happen in method ScheduleTaskInternal in DurableTask.Core.TaskOrchestrationContext.

When we reach this line :
`var tcs = new TaskCompletionSource<string>();
string serializedResult = await tcs.Task;`

Then its lost. I noticed that the tcs.Task has a null value for the attribute "method", im not sure if it has something to do with my problem.

**Comment by xTeKillax** [comment]
I've solved my problem by creating a new class inheriting ObjectCreator<T>
In this class I use LambdaExpression to instanciate my TaskActivity with the proper constructor.
My startup then pass the mediatr which was injected in its constructor:

`taskHub.AddTaskActivities(new ObjectCreator<TaskActivity>[]
            {
                new WorkerObjectCreator<TaskActivity>(typeof(UpdateOperationStatusActivity), _mediatr)
            });`

Its not sexy, but for now this is working
