### ISSUE TITLE
Make DurableTask.AzureStorage TimeoutHandler customizable

### ISSUE THREAD

**Issue by stratever** [Azure/durabletask#355]
Given a Azure Durable Function running in on-remise docker container. We've received an error:

> [0m The operation 'GetMessage' with id 'c563e849-8eb3-4fd5-85e1-11c10b8600d8' did not complete in '00:02:00'. Terminating the process to mitigate potential deadlock.

which is expected according to the following implementation:
https://github.com/Azure/durabletask/pull/323

By running the function in docker, we need to take care about the auto-restart which is still something we can live with. However, the current implementation can be improved to give flexibility to the developer to handle this case better than letting the function hanging for 2 minutes and terminating the process. Here's a possible improvement:

The timeout can happen due to network issue (the network goes away and then comes back) maybe it worth to retry the invocation instead of waiting 'till timeout and killing the process (as it's not a deadlock scenario). So let's say, keep the 2 minutes timeout as is, but internally it can retry the operation (assuming that the operation is idempotent, I think it should be) - so sending the same request (regardless the result of the previous invocations) shouldn't cause issue or inconsistency but please correct me if I'm wrong. By resolving the TimeoutHandler from container and making it injectable somehow would be a great option but I'm happy to contribute and discover further options. 

PS: I think the 2 minutes is a quite high threshold anyway

**Comment by cgillum** [comment]
How likely is it that a 2+ minute delay is caused by the network going away and not by a deadlock? I would normally expect a timeout or network exception to be thrown in less time than this.

I worry a little about how this could potentially go wrong. For example, if we retry deadlocked API calls, that could cause us to leak threads and memory over time since we don't have a way to abort the deadlocked threads. Accounting for this case could make the code a lot more complex and hard to test.

Maybe it would help if you could elaborate more on why the force-termination is problematic for your use case?

**Comment by stratever** [comment]
> How likely is it that a 2+ minute delay is caused by the network going away and not by a deadlock? I would normally expect a timeout or network exception to be thrown in less time than this.

Yes, I would expect an exception but it seems this isn't the case. We've got a build agent with an unstable network connection (network interference in the background) and the integration tests used to fail with this error (sometimes there are 5-9x forced-termination during the 20-30mins test execution) and it only happens on that particular server this is why I think it relates to a network issue rather than a proper deadlock scenario. What I can imagine is the storage service returns a proper 200 status code but the client disappear before (or meanwhile) reading the response stream or the server lost the client before sending the response? (afaik even in this case an exception should occur....)

> I worry a little about how this could potentially go wrong. For example, if we retry deadlocked API calls, that could cause us to leak threads and memory over time since we don't have a way to abort the deadlocked threads. Accounting for this case could make the code a lot more complex and hard to test.

My suggestion is not about converting the default behavior to a retry based solution but give flexibility to the developers to handle that case on their own by making the timeouthandler configurable or customizable.  Let's say we retry the API call only 2x. If the second invocation keeps hanging as the first one and the operation task doesn't return in an 'acceptable' timeframe ( < 2 sec) then yes, it may be a deadlock and no further retry required so we can terminate the process, but if the second invocation successful and the operation returns then we can just cancel the first operation task. 

> Maybe it would help if you could elaborate more on why the force-termination is problematic for your use case?

The test execution scenario above may tells that the force-termination could even happen in case of a network error. And force-termination should only be triggered in a real deadlock scenario.

**Comment by ferike86** [comment]
@cgillum Any update on this issue?

**Comment by MaxHogervorst** [comment]
> How likely is it that a 2+ minute delay is caused by the network going away and not by a deadlock? I would normally expect a timeout or network exception to be thrown in less time than this.
> 
> I worry a little about how this could potentially go wrong. For example, if we retry deadlocked API calls, that could cause us to leak threads and memory over time since we don't have a way to abort the deadlocked threads. Accounting for this case could make the code a lot more complex and hard to test.
> 
> Maybe it would help if you could elaborate more on why the force-termination is problematic for your use case?

https://docs.microsoft.com/en-us/partner-center/develop/get-invoice-unbilled-consumption-lineitems#rest

This api is very slow....

**Comment by ConnorMcMahon** [comment]
@MaxHogervorst, to clarify, the 2 minute timeout that we have is just for Azure Storage operations. It should not force any activity/orchestration code to complete within 2 minutes. The timeout should only be hit if we hit a deadlock in the Storage SDK or your storage account is unhealthy for some reason.

If you are finding that the length of your own code is affected by our timeout behavior, that is a bug that we will need to fix.

**Comment by cgillum** [comment]
We recently received support for TimeoutHandler customization as an accepted PR contribution: https://github.com/Azure/durabletask/pull/536. It should be available in the latest published nuget packages.
