### ISSUE TITLE
DispatchMiddlewareContext ctor should be public

### ISSUE THREAD

**Issue by jviau** [Azure/durabletask#388]
Having the constructor for this type internal makes it difficult to unit test middleware as you cannot create one of these for testing.

Is there any particular reason the constructor is internal?

**Comment by cgillum** [comment]
No specific reason that I can recall. I think we can consider making this public.

**Comment by saguiitay** [comment]
Submitted a PR #546

**Comment by cgillum** [comment]
Thanks! The PR has been merged and I've published an updated nuget package that includes this fix: https://www.nuget.org/packages/Microsoft.Azure.DurableTask.Core/2.5.5
