### ISSUE TITLE
Improve DurableTask.AzureStorage partition management

### ISSUE THREAD

**Issue by cgillum** [Azure/durabletask#410]
## Overview
The **DurableTask.AzureStorage** provider uses partitioning and blob leases to ensure that an orchestration instance runs on only one worker instance at a time. More details on this design can be found [here](https://github.com/Azure/durabletask/tree/master/src/DurableTask.AzureStorage#partitioning). When the app is scaled out to additional workers, the new workers will attempt to steal partition leases to properly balance the distribution of partitions across all workers.

This stealing can be problematic because it is not cooperative. "Split-brain" can occur if a worker is executing an orchestration instance that is assigned to a particular partition and that partition is stolen by another worker mid-execution. In many cases, the result is often duplicate activity execution. When sub-orchestrations are involved, the impact of duplicate execution could be even more severe.

This issue tracks changing the partition management to remove the split-brain risks associated with lease stealing.

## Proposed design
One of the primary design goals is to try to _extend_ the existing design to minimize risks associated with code churn. This is the proposal I came up with, which I briefly discussed with @sebastianburckhardt a while back, in bullet-list form:

- There are _two_ lease blobs for each partition: an **intent** blob and an **ownership** blob.
- A worker will only poll for messages in a queue if it owns **both** the _intent_ and _ownership_ blob leases.
- All nodes try to acquire _intent_ lease blobs. If there is an imbalance, _intent_ leases can be stolen to create balance.
- For the most part, _intent_ lease management uses the exact same algorithm as the existing lease manager.
- Nodes poll for _ownership_ leases only if they own the corresponding _intent_ lease. _Ownership_ leases are never stolen.
- If an _intent_ lease is stolen, the holder of the corresponding _ownership_ lease must stop processing new messages for that lease. Once all messages for that lease are drained. They will release the ownership lease so that it can be acquired by the new owner of the _intent_ lease.

### Suggested polling frequencies (TBD)

  | Polling frequency | Renewal frequency | Lease lifetime
-- | -- | -- | --
Intent blob |   |   |  
Ownership blob |   |   |  

## Benefits
- Eliminates split-brain in the happy path. Lease transitions are cooperative.
- No additional overhead in steady state compared to current model.
- The design is relatively simple and easy to understand.

## Disadvantages
- Lease transitions are slower. This can result in lower scale-out speed for entities and orchestrations.

**Comment by olitomlinson** [comment]
> Lease transitions are slower. This can result in lower scale-out speed for entities and orchestrations.

From what I understand of the design, I'm assuming the magnitude of this slow down of scale-out is more towards negligible rather than significant? (asking as someone who has a use-case that requires a degree of scale-out consistency due to SLAs)

**Comment by cgillum** [comment]
I think it's fair to say this is _mostly_ negligible, but it depends on how sensitive your app is to handling sudden increases in load. The speed at which a Durable app scales out doesn't actually change, but the time it takes for us to load balance partitions across those app instances will take longer. There will be no impact to how quickly activity functions can use the new compute. However, orchestrations and entities will need to wait a little longer before being moved to the new instances. The additional time being added is the time it takes to drain all work for a particular partition off of one VM so that a new instance can start processing that load. For orchestrations it should be relatively fast because they don't tend to stay in memory very long. Entities could take longer if there are in-flight operations that take a long time to complete.

**Comment by ConnorMcMahon** [comment]
In initial performance tests, a scenario in which I ran the following orchestration with 20,000 as the input:

Note these numbers are preliminary for my PR, as there is still some ironing out to do and tweaking of the intervals, but performance drops so far are not quite negligible, but not awful.

```csharp
        [FunctionName("StartLoad")]
        public static async Task<HttpResponseMessage> Start(
            [HttpTrigger(AuthorizationLevel.Function, methods: "post", Route = "StartLoad")] HttpRequestMessage req,
            [DurableClient] IDurableOrchestrationClient starter,
            ILogger log)
        {
            int num = await req.Content.ReadAsAsync<int>();
            if (num <= 0)
            {
                return req.CreateErrorResponse(HttpStatusCode.BadRequest, "A positive integer was expected in the request body.");
            }
            string instanceId = await starter.StartNewAsync<object>("Orchestrator", num);
            log.LogInformation("Started FanOutFanInOrchestration orchestration with ID = '" + instanceId + "'.");
            return starter.CreateCheckStatusResponse(req, instanceId);
        }

        [FunctionName("Orchestrator")]
        public static async Task Orchestrator([OrchestrationTrigger] IDurableOrchestrationContext ctx)
        {
            int numSubOrchestrations = ctx.GetInput<int>();
            var tasks = new List<Task>();
            for (int i = 0; i < numSubOrchestrations; i++)
            {
                tasks.Add(ctx.CallSubOrchestratorAsync(nameof(SubOrchestrator), null));
            }

            await Task.WhenAll(tasks);
        }


        [FunctionName("SubOrchestrator")]
        public static async Task<string> SubOrchestrator([OrchestrationTrigger] IDurableOrchestrationContext ctx)
        {
            string[] phrases = new string[3];
            phrases[0] = await ctx.CallActivityAsync<string>(nameof(Activity), "Seattle");
            phrases[1] = await ctx.CallActivityAsync<string>(nameof(Activity), "London");
            phrases[2] = await ctx.CallActivityAsync<string>(nameof(Activity), "Tokyo");
            return string.Join(';', phrases);
        }

        [FunctionName("Activity")]
        public static string Activity(
            [ActivityTrigger] IDurableActivityContext ctx)
        {
            return $"Hello {ctx.GetInput<string>()}";
        }
```

With current partition management:

**Run 1:**
Time: 00:25:59
Split brain: Yes
![image](https://user-images.githubusercontent.com/8934380/88952160-e2f04a00-d24b-11ea-9e47-d48eaaceab61.png)

**Run 2:**
Time:  00:24:00
Split brain: Yes
![image](https://user-images.githubusercontent.com/8934380/88952292-13d07f00-d24c-11ea-979a-afb1a0e3399d.png)


With new partition management:

**Run 1:**
Time: 00:29:33
Split brain: No
![image](https://user-images.githubusercontent.com/8934380/88952409-424e5a00-d24c-11ea-8b8c-bd2398cc6b4d.png)


**Run 2** (tweaked some parameters on ownership lease intervals)
Time: 00:31:41
Split brain: No
![image](https://user-images.githubusercontent.com/8934380/88952815-caccfa80-d24c-11ea-949b-49212d7a06da.png)

**Comment by olitomlinson** [comment]
So roughly a 20% increase in time to scale-out? Its not outrageous, but it is significant. However it would _probably_ slip under the radar of my users.

I'm wondering if it might be beneficial to have this as a configuration option? I've only ever witnessed split brain when dealing with Entities. So if I had the choice, I'd likely keep my existing SLA sensitive App which only uses Orchestrations on the current lease management strategy, however my new app which uses Entities I would use the new strategy. Not having the option is not a deal breaker though.

**Comment by ConnorMcMahon** [comment]
Note that this is a relatively early draft of this new approach, and there may be bugs to fix and/or intervals to tweak that will reduce that scale out increase.

**Comment by cgillum** [comment]
This work was completed as part of PR https://github.com/Azure/durabletask/pull/427
