### ISSUE TITLE
Can you add documentation around Generations

### ISSUE THREAD

**Issue by ranganathg** [Azure/durabletask#413]
I am going through this wiki https://github.com/Azure/durabletask/wiki/Writing-Task-Orchestrations and it says the Generations are described below but I didn't find any documentation around it. Can you add that?

_The execution history of an orchestration has a record of all scheduled task activities and their results. This history is also bounded by size limitations of Service Bus so as a consequence, infinite loops are not possible without user-aided checkpointing (**described under Generations below**)._

**Comment by cgillum** [comment]
I'm guessing this was a documentation refactoring bug around the time the article was published. I think the original authors intended to link to the [Eternal Orchestrations](https://github.com/Azure/durabletask/wiki/Feature---Eternal-Orchestrations-%28aka-infinite-loops%29) topic (which starts out by referencing execution history "above").

**Comment by cgillum** [comment]
I went ahead and fixed this. Thanks for brining it to our attention.
