### ISSUE TITLE
Managed Identity support for DurableTask.ServiceBus

### ISSUE THREAD

**Issue by AlexKuriatnyk** [Azure/durabletask#414]
Right now ServiceBusOrchestrationService accepts only Service Bus connection string. Do you have any plans to also accept endpoint/TokenProvider, so we can use Managed Identity or AAD authentication instead?

**Comment by cgillum** [comment]
The DurableTask.ServiceBus package no longer has active maintainers so it's effectively in "community mode" at this point. We're willing to review and accept PRs for new features like this, if you or someone else is willing to contribute them.

**Comment by jump523steps** [comment]
Is there a "community mode" & "official mode" list of the backend providers? @cgillum

**Comment by AlexKuriatnyk** [comment]
@cgillum , sounds good. I can create a PR with needed changes to support this feature.

**Comment by cgillum** [comment]
@jump523steps we don't have a list, but I can probably add one to the README (the README badly needs an update anyways). Right now I can tell you that DurableTask.AzureStorage is the only backend that is being actively supported by Microsoft at this time.

**Comment by cgillum** [comment]
@AlexKuriatnyk that would be great! I'll keep an eye out for your PR. Once merged, we can publish the updated version of DurableTask.ServiceBus to nuget.org as part of our existing release cadence.
