### ISSUE TITLE
Question: When can we expect the sql server implementation as nuget package

### ISSUE THREAD

**Issue by ankituipath** [Azure/durabletask#433]
I am looking to consume the sql implementation which was recently added in my project and was curious what are the plans to release the sql implementation as nuget package? 
Thanks for adding that functionality though. Its really cool to see :)

**Comment by cgillum** [comment]
We don't have any concrete plans yet. Can you tell me about how you intend to use it?

Part of the reason I ask is that there are actually two different SQL projects going on right now. The code [here](https://github.com/Azure/durabletask/tree/master/src/DurableTask.SqlServer) is a community contribution that only implements a SQL-based instance store. We have another project outside of this repo that implements a full orchestration service on SQL Server, including both tracking and orchestration processing. I want to make sure I correctly understand which one you're interested in.

**Comment by bendursley** [comment]
Hi @cgillum are you able to share any more information on the full orchestration service on SQL Server?

With the checked in code in DurableTask.SqlServer, would this work in conjunction with the Azure Storage for the leases etc, but the Task Hub tables would be stored in SQL?

**Comment by bendursley** [comment]
@cbrianball - your work the with DurableTask.SqlServer code - do you have an sample function app with how you'd use it with dependency injection during function startup?  Have tried (And failed) to get it working so far :(

**Comment by cbrianball** [comment]
@bendursley Sorry, I do not have an example. The project I originally wrote this for went in a different direction, so I never actually used it in a production environment. My guess would be that this is a higher-level question about how to use IoC within Durable Task.

One clue might be in how Azure Web Job SDK handles IOC. There's an extension for that SDK that uses Durable Task, you might want to look at how they solved it.

**Comment by cgillum** [comment]
@bendursley 

> Hi @cgillum are you able to share any more information on the full orchestration service on SQL Server?

Sure, the full SQL server-based backend can be found here: https://github.com/cgillum/durabletask-sqlserver. It's currently in prototype mode, but it allows you to run some basic orchestrations with a SQL backend. The DurableTask.SqlServer.AzureFunctions project/nuget package reference automatically takes care of the dependency injection. There is a performance testing project in that repo that has an example of a function app that uses it.

I'm hoping we can do an official "preview" release of this by the end of this calendar year.

**Comment by bendursley** [comment]
@cgillum We'd definitely be interested in picking up an official preview when you get to it at the end of the year!

**Comment by cgillum** [comment]
An official SQL Server implementation is now available. It's technically considered public preview right now, but will reach "GA" by the end of this calendar year.

* GitHub repo: https://github.com/microsoft/durabletask-mssql
* NuGet package: https://www.nuget.org/packages/Microsoft.DurableTask.SqlServer/
* Documentation: https://microsoft.github.io/durabletask-mssql
