### ISSUE TITLE
Table Storage exception due to exceeding max message size

### ISSUE THREAD

**Issue by seancolonello** [Azure/durabletask#448]
After upgrading to v1.8.0 I started getting exceptions related to Table storage. The issue is caused by pull request #435, the new max size calculation isn't correct.

This content (37,913 bytes UTF8)...
[rawContent.txt](https://github.com/Azure/durabletask/files/5152330/rawContent.txt)
...causes the problem when found here...
https://github.com/Azure/durabletask/blob/3a07d8d65b84fda6ebc8289cce9a6bec1269cad2/src/DurableTask.AzureStorage/MessageManager.cs#L90-L94

Below is trace output from Azure functions.
> [8/31/2020 4:18:28 PM] Microsoft.WindowsAzure.Storage.StorageException: Bad Request
> [8/31/2020 4:18:28 PM]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
> [8/31/2020 4:18:28 PM]    at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.SetNewExecutionAsync(ExecutionStartedEvent executionStartedEvent, String eTag, String inputStatusOverride) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 845
> [8/31/2020 4:18:28 PM]    at DurableTask.AzureStorage.AzureStorageOrchestrationService.CreateTaskOrchestrationAsync(TaskMessage creationMessage, OrchestrationStatus[] dedupeStatuses) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 1362
> [8/31/2020 4:18:28 PM]    at DurableTask.Core.TaskHubClient.InternalCreateOrchestrationInstanceWithRaisedEventAsync(String orchestrationName, String orchestrationVersion, String orchestrationInstanceId, Object orchestrationInput, IDictionary`2 orchestrationTags, OrchestrationStatus[] dedupeStatuses, String eventName, Object eventData, Nullable`1 startAt) in C:\source\durabletask\src\DurableTask.Core\TaskHubClient.cs:line 608
> [8/31/2020 4:18:28 PM]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.StartNewAsync[T](String orchestratorFunctionName, String instanceId, T input) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs:line 149
> [8/31/2020 4:18:28 PM]    at Relia.Service.Crm.CrmOperations.Crm_Dispatch(Message message, IDurableOrchestrationClient starter, IDurableEntityClient entityClient, ILogger log) in C:\dev\Relia.Service\src\Relia.Service\Crm\CrmOperations.cs:line 72
> [8/31/2020 4:18:28 PM] Request Information
> [8/31/2020 4:18:28 PM] RequestID:62676ef5-d91c-48cc-8c22-f808a6d9a49b
> [8/31/2020 4:18:28 PM] 77fce39d8d45499295c549f5fbbe38e3: No history events were found
> [8/31/2020 4:18:28 PM] RequestDate:Mon, 31 Aug 2020 10:18:28 GMT
> [8/31/2020 4:18:28 PM] StatusMessage:Bad Request
> [8/31/2020 4:18:28 PM] ErrorCode:
> [8/31/2020 4:18:28 PM] ErrorMessage:The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.
> RequestId:62676ef5-d91c-48cc-8c22-f808a6d9a49b
> Time:2020-08-31T16:18:28.0953183Z
>

**Comment by cgillum** [comment]
@ConnorMcMahon FYI, I think the size calculation fix we made was correct for Azure Storage queues but not correct for Table Storage. :(
