### ISSUE TITLE
Redis implementation is far from complete！！！

### ISSUE THREAD

**Issue by JiangTaoShi** [Azure/durabletask#453]
By publish and subscribe ,Do you support multiple HubWoker deployments？

**Comment by ChenglongLiu** [comment]
Redis implementation is not actively maintained.

**Comment by ConnorMcMahon** [comment]
@JiangTaoShi,

We are currently tracking the progress on the Redis worker in issue #253, so I am going to close this issue as a duplicate.

As for the state of the provider, we currently are not actively working on it, as the team maintaining it did not have the resources to bring it into a stable state. That being said, we are happy to accept contributions to the project.
