### ISSUE TITLE
Project: Durable Task Extensions

### ISSUE THREAD

**Issue by lucaslorentz** [Azure/durabletask#486]
I'm creating a project that concisely extends what Durable Task project already delivers:
https://github.com/lucaslorentz/durabletask-extensions

This would be the scope of the project:
- More interfaces defining storage features
- Dependency injection integration
- EF Core MySql/PostgreSQL/SqlServer storages
- Distributed workers: Allows splitting orchestrations/activities implementation in multiple workers
- Indirect storage access via GRPC protocol: Centralize your storage choice and configuration in a single component.
- UI
- BPMN runner (not sure yet)

I still don't know how far I will go with that project.

So I would like to get some feedback if it would be useful to anyone, or if it conflicts with other projects or plans.

Screenshot of history visualization in UI :-)
![image](https://user-images.githubusercontent.com/2268284/102087753-4acdb880-3e1a-11eb-89fc-f2d57c31046e.png)

**Comment by cgillum** [comment]
Very cool! A couple other projects to be aware of:

* [DurableTask.SqlServer](https://github.com/cgillum/durabletask-sqlserver): This is a Microsoft SQL-based backend that is under active development. It's not generic enough to support MySQL or PostgreSQL, so what you're doing might be more accessible to a broader audience.
* [DurableTask-Hosting](https://github.com/jviau/durabletask-hosting): This is a project that adds some hosting features on top of DTFx, including dependency injection.

Generally speaking, all of your planned items are things that I think would be very helpful for the project. There may be potential opportunities for alignment regarding some of the projects mentioned above as well. Let us know how we can help.

**Comment by lucaslorentz** [comment]
Thanks @cgillum

I would need other storage implementations, like [DurableTask.SqlServer](https://github.com/cgillum/durabletask-sqlserver), to implement some additional contracts I defined:

- [IExtendedOrchestrationService](https://github.com/lucaslorentz/durabletask-extensions/blob/main/src/LLL.DurableTask.Core/IExtendedOrchestrationService.cs) would be a way to improve intercommunication between durable functions by sharing the same storage on all of them. Related to: https://github.com/Azure/azure-functions-durable-extension/issues/156
- [IExtendedOrchestrationServiceClient](https://github.com/lucaslorentz/durabletask-extensions/blob/main/src/LLL.DurableTask.Core/IExtendedOrchestrationServiceClient.cs) Defines contracts for features already implemented by Azure Storage. I use this contract to have interchangeable storage in the Durable Task UI.

Any thoughts about those contracts?
I can PR those contracts into this repo to trigger a discussion.

**Comment by cgillum** [comment]
@lucaslorentz this is a very ambitious project, I like it! It's great to see you have some experience with Cadence as well since I think it would be good to adopt some of their learnings back into DTFx. 

Regarding `IExtendedOrchestrationService` and `INameVersionInfo[]`. I like this idea because of how it would allow you to isolate particular activities and orchestrations to specific workers. However, existing providers like DT.ServiceBus and DT.AzureStorage have a shared queue model where all orchestration events and tasks go through a shared set of queues. There's also the problem of being able to filter messages without any embedded name/version information. Should I assume that this interface is only intended for newer SQL-based storage providers?

How far along are your prototype providers? I think I'd feel okay taking some of these extensions into DT.Core if you think they are stable.

Also, have you considered abstract base classes over interfaces as a way to continue extending the functionality without needing to introduce even more interfaces (i.e. to avoid breaking changes)?

**Comment by lucaslorentz** [comment]
Actually, I have no practical Cadence experience, just read docs and source code.

> Should I assume that this interface is only intended for newer SQL-based storage providers?

That's a fair assumption. I think it would be implemented first by new SQL-based providers. But I think other providers could follow in the future as well.

When implementing that on SQL I found out that using `IN` and `OR` to filter queues affects the index scan and consequentially locks scanned rows from "other queues".

The approach ended up doing is to [shuffle the queues and try to dequeue from each one](https://github.com/lucaslorentz/durabletask-extensions/blob/03e30f5aec3472ea0e08121fecf9279ccf5f4cff/src/LLL.DurableTask.EFCore/EFCoreOrchestrationService.cs#L445). I guess it would be possible to implement this approach on any "pull to dequeue" provider?

> How far along are your prototype providers?

The providers are functional.

The samples folder has a fully working example of a microservices architecture like this [diagram](https://github.com/lucaslorentz/durabletask-extensions/blob/main/readme/diagrams/architecture_1.png). Which involves EFCore + GRPC providers.

But I haven't test anything on a real application or production environment. A lot of testing and fine tunning is still required.

**Comment by lucaslorentz** [comment]
> Also, have you considered abstract base classes over interfaces as a way to continue extending the functionality without needing to introduce even more interfaces (i.e. to avoid breaking changes)?

I think it might be a better option indeed for an evolving contract.

I can use C# 8 default interface implementation in my repo.
Not sure if Durable Task can use it because it requires netstandard2.1.

**Comment by lucaslorentz** [comment]
@cgillum 

> There's also the problem of being able to filter messages without any embedded name/version information

That's only the case for raising events and termination or orchestration, right?  
Providers that use real queues could query the name/version of the instance before putting the message in the queue.  
Not optimal, but I don't see many use cases as well with intensive message sending to orchestrations, I would assume it's acceptable to add delays to those operations.

**Comment by lucaslorentz** [comment]
@cgillum 

In the end, I implemented the way I described above:
In [SendTaskOrchestrationMessage](https://github.com/lucaslorentz/durabletask-extensions/blob/2f1285441e9ea3e24700959582e34486ae8e1cc7/src/LLL.DurableTask.EFCore/EFCoreOrchestrationServiceClient.cs#L137) I query the current queue (name+version) of the target instanceId.
During [orchestration task completion](https://github.com/lucaslorentz/durabletask-extensions/blob/2f1285441e9ea3e24700959582e34486ae8e1cc7/src/LLL.DurableTask.EFCore/EFCoreOrchestrationService.cs#L350) it's possible to know the queue for all messages to be sent.
And I store reply queue information within every [task activity message created](https://github.com/lucaslorentz/durabletask-extensions/blob/2f1285441e9ea3e24700959582e34486ae8e1cc7/src/LLL.DurableTask.EFCore/EFCoreOrchestrationService.cs#L354).

I'm stabilizing the project with tests and I will continue exploring the distributed workers concept.
