### ISSUE TITLE
DTFx.AzureStorage not honoring DataContract on OrchestrationInstance during serializing

### ISSUE THREAD

**Issue by jviau** [Azure/durabletask#491]
`OrchestrationInstance` is marked with `DataContract` and has an `ExtensionData` object on it. This is to allow round-trip serialization when the types do not exactly match on each end, without losing any data. Unfortunately, AzureStorage is using custom Newtonsoft Json serialization with `TypeNameHandling.Object` and an `ISerializationBinder` which drops assembly name. The result is that AzureStorage implementation cannot round-trip any OrchestrationInstance serialization that has a change in type name. This means that any refactor that changes OrchestrationInstance full name will break ongoing orchestrations, and it outright prevents any use of custom OrchestrationInstance implementations (which is possible with other providers, like ServiceBus).

Luckily Newtonsoft.Json does honor `DataContract` attributes already, the fix should be as simple as adding `[JsonProperty(TypeNameHandling = TypeNameHandling.None)]` to `MessageData.Sender`.

**Comment by cgillum** [comment]
@jviau can you provide an example scenario that requires custom, serializable `OrchestrationInstance` types with DTFx? I was not involved in the project when this type was originally designed and therefore don't have a sense for how to prioritize fixing the current DTFx.AzureStorage behavior.

**Comment by jviau** [comment]
@cgillum I use custom `OrchestrationInstance` to flow a general bag of metadata with a given orchestration. This is useful for setting something like a `CorrelationId` for an orchestration, all of its sub orchestrations, and activities. Here is an example of how I do it: https://github.com/jviau/durabletask-hosting/tree/master/samples/DurableTask.Samples/SessionData (all 3 files).

I am sure this is not an _officially_ supported scenario, but since `OrchestrationInstance` is marked with `DataContract`, it _should_ work so long as everyone honors that contract.

The other issue here, is if `OrchestrationInstance` is ever renamed, or has its namespace changed, all running orchestrations for AzureStorage will break when upgrading. This can be avoided by not having `TypeNameHandling.Objects`. I put up a PR to do a quick fix for just this one object, but as I mentioned there, AzureStorage may want to evaluate dropping that TypeNameHandling altogether or rethink it at least.

**Comment by cgillum** [comment]
Thanks for this additional context. Your correlation scenario is quite interesting. I also agree with your point about the potential fragility around type renames (I recall that the Service Bus provider maintainers had to do a lot of work related to this at one point).

I looked at your PR and it's pretty minimal, so I think it should be fine to accept. I'm less confident about whether we can change the default behavior for _all_ serialization because of the potential impact to assembly load behavior in certain host environments (Azure Functions comes to mind) but we can probably look at some of these improvements on a case-by-case basis.

**Comment by jviau** [comment]
Closed by #492

**Comment by jviau** [comment]
Re-opening as I incorrectly assumed Newtonsoft.Json honored `IExtensibleDataObject` contract. It does not, so extra properties on a more derived `OrchestrationInstance` are lost during serialization. This will need to be fixed to correctly honor the contract.
