### ISSUE TITLE
AzureStorage: Large orchestrationInstances are corrupted, causing discarded messages

### ISSUE THREAD

**Issue by chrissmiller** [Azure/durabletask#525]
Large orchestrationInstances (>~16kb) are being sent to table storage as a DurableTask.Core.History.GenericEvent rather than an ExecutionStartedEvent. When the framework pulls the history event, it is discarded with this error: "Discarding 1 dequeued history event(s): Instance is corrupted." The corruption seems to be because the framework cannot find an ExecutionStartedEvent. The issue is not specific to the activity/orchestration being sent, just on the size of the data. We checked to see if it was a specific range of sizes, but this occurs for a message of about 150kb as well.

This issue causes any orchestrations with enough data to fail somewhat silently  -- the first activity will execute, then the task completed message will be discarded without any exception or indication that orchestration size is the issue.

Is this intended behavior? We would expect that we would receive an exception if the orchestration instance is too large, but not sure if we are perhaps doing something wrong here.

Type and the start of data for a message this occurs for:
```
"$type": "DurableTask.Core.History.GenericEvent, DurableTask.Core",
"Data": "{\r\n  \"$type\": \"DurableTask.Core.History.ExecutionStartedEvent, DurableTask.Core\",\r\n  \"OrchestrationInstance\":
```

The exact same orchestration type, but with slightly less data in the actual OrchestrationInstance
```
"$type": "DurableTask.Core.History.ExecutionStartedEvent, DurableTask.Core",
"OrchestrationInstance":
```

Happy to provide more information/examples to assist with debugging

**Comment by cgillum** [comment]
I’ve never heard of this kind of behavior.  What versions of the nuget packages are you using? Do you have a simple repro project you can share?

**Comment by ConnorMcMahon** [comment]
I ended up seeing this today. Make sure that you are not using the `AzureTableInstanceStore` used by the DurableTask.ServiceBus project as an `IOrchestrationServiceInstanceStore` passed to your `AzureStorageOrchestrationService`. For some reason, it looks like we use the `IOrchestrationServiceInstanceStore` in some code paths, but not others.

In general, DurableTask.AzureStorage used it's own interface for custom instance stores, and I'm not entirely sure why, but it appears that it does not play nicely with the Service Bus instance store implementation with large messages.

**Comment by chrissmiller** [comment]
I believe this is the culprit -- apologies for the delayed response; I was trying to repro it in a small project, but had excluded the code where we were using AzureTableInstanceStore so had not been able to yet. I'll close this as soon as I've verified that that removing that solves the problem. Thank you for your help!

**Comment by chrissmiller** [comment]
Validated that removing the use of AzureTableInstanceStore appears to solve the problem. Thanks again!

**Comment by vany0114** [comment]
@cgillum @ConnorMcMahon  I'm experiencing this issue, I'm using the JS SDK to orchestrate a couple of timers, this error is causing the timer never to get fired off, any idea?

![image](https://user-images.githubusercontent.com/12032625/153081953-4cbd54d0-c6f7-4546-aa9c-1c28b30a25af.png)

Thanks in advance.

**Comment by cgillum** [comment]
Hi @vany0114. You mentioned you're using a JS SDK. Would you mind opening an issue here so that we can get the right folks to take a look? https://github.com/Azure/azure-functions-durable-js/issues. FYI @davidmrdavid 

BTW, Connor is no longer working on the project, but I think David should be able to help.
