### ISSUE TITLE
Race condition between orchestration (re)start and external events cause orchestrations to get stuck in Pending status

### ISSUE THREAD

**Issue by cgillum** [Azure/durabletask#530]
This is the root cause of https://github.com/Azure/azure-functions-durable-extension/issues/1715.

The problematic scenario is the following:

* Restarting an instance of a completed orchestration
* At the same time, sending an external event to the restarting instance

The history prefetch behavior of DT.AzureStorage loads the old instance history because it sees the external event message first. It then adds the ExecutionStarted message to the same batch, thus associating it with the old history. Once the batch is executed as a session, both the ExecutionStarted and external event messages are discarded because the orchestration runtime state that got loaded is in the "Completed" state. This leaves the instance status (in the Instances table) stuck in Pending.

What should have happened is that we process the ExecutionStarted message separately from the event raised messages. This would allow us to load the correct (empty) history and start the new orchestration generation successfully. The relevant code that needs to be tweaked is [here](https://github.com/Azure/durabletask/blob/18962b891cf9693509bd476ff8cb0bd9de2633ad/src/DurableTask.AzureStorage/OrchestrationSessionManager.cs#L408-L430).

The workaround is to restart the orchestration again with another ExecutionStarted message.

**Comment by davidmrdavid** [comment]
Fixed in: https://github.com/Azure/durabletask/pull/531
