### ISSUE TITLE
Log exceptions in tracking dispatcher

### ISSUE THREAD

**Issue by affandar** [Azure/durabletask#55]
TrackingDispatcher:

           {
               // TODO : send batch to instance store, it can write it as individual if it chooses
               foreach (OrchestrationStateInstanceEntity stateEntity in stateEntities)
               {
                   await InstanceStore.WriteEntitesAsync(new List<OrchestrationStateInstanceEntity> { stateEntity });
               }
           }
           catch (Exception e) when (!Utils.IsFatal(e))
           {
               TraceEntities(TraceEventType.Critical, "Failed to write state entity", stateEntities, GetNormalizedStateEvent);
               throw;
           }

<b>tracing the exception would have been very useful here.<b>

**Comment by cgillum** [comment]
Closing out old issues. The current exception logging is pretty good, so this is likely resolved. :)
