### ISSUE TITLE
DTFx Distributed Tracing Issues

### ISSUE THREAD

**Issue by jviau** [Azure/durabletask#559]
# DTFx Distributed Tracing Issues

I have dug into DTFx distributed tracing and have built up a list of issues and areas I would like to see improved. I am very happy to see distributed tracing be part of DTFx, and the current implementation does certainly allow for some degree of tracing. But to be honest, I have found it to be very difficult to work with. Many expectations I have with distributed tracing when comparing to other examples, such as AspNetCore request in tracing, or the HTTP request out diagnostics, DTFx falls short on many areas.

I highly recommend DTFx study other examples, and also study OpenTelemetry specification and bring the distributed tracing support in DTFx up to those standards. DTFx is an incredibly useful tool, but one of the biggest hurdles is diagnosing when something goes wrong. It is very hard to understand when an orchestration is failing - especially when it fails in the middleware pipeline or the base framework itself (as in, before it ever gets to executing the orchestration). Having solid, reliable, plug and play tracing would be an amazing value to have with DTFx. Unfortunately, I do not feel like the current implementation accomplishes this yet.

## Issues

Here is a list of issues I have encountered, but it is by no means complete.

1. Request/Dependency telemetry does not include success or failure.
    - To use app insights as an example, there is no information on what to set `RequestTelemetry.Success` and `DependencyTelemetry.Success` to.
2. Request/Dependency telemetry does not include general metadata about the orchestration or activity executed.
    - If you compare to other events, such as the HTTP message out event, they will include the full HTTP request. Or the AspNetCore HTTP request in, the HTTP Context is included. This is very useful for including customized information.
    - Recommendation is that DTFx includes a type of context object regarding what was / is being executed.
3. Does not follow proper started & stopped events.
    - Again, comparing to other distributed tracing implementations they follow the same pattern for naming events, and including a started and stopped event. DTFx does not do this.
    - Due to the distributed nature of DTFx, implementation of Start and Stop events will require some thinking.
4. Inconsistent usage for `System.Diagnostics.Activity.Current`. In some cases, such as `TaskActivity` execution, the diagnostics activity is always present. For orchestrations it is only present _sometimes_.
    - It would be immensely helpful for the `TraceContextBase` to become an implementation detail only and no longer be visible to DTFx consumers. Instead, DTFx should expose all of its tracing through `System.Diagnostics.Activity`.
    - Again, with the distributed nature and the disconnect between an orchestration start and stop, this poses a challenge as an Activity's `SpanId` is not settable and always generated on start. A quick workaround is to simply use reflection to set this. I have successfully accomplished this myself.
5. Implementation has application insights specific concepts leaked into it.
    - Not everyone uses application insights.
    - The implementation has an assumption you can hook into your telemetry pipeline and set extra values based on `CorrelationTraceContext.Current` - this is not always the case.
6. `Activity.Baggage` is not respected. The contents of this enumerable should flow through DTFx execution.
    - For example, ServiceBus client will copy `Activity.Baggage` into message properties [here](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/servicebus/Microsoft.Azure.ServiceBus/src/ServiceBusDiagnosticsSource.cs#L650). Outgoing HTTP calls will also include `Activity.Baggage` into a header.
7. Performance concerns. Telemetry is often part of a hot path, and should have minimal performance impact. The current implementation performs a lot of serialization, and potentially even excess serialization.
    - To highlight just how important it is for telemetry to have a minimal performance impact, libraries often go as far as avoiding singular string allocations in places. For example, aspnetcore does not use the `DiagnosticSource.StartActivity` method as it involves a _single_ string allocation. Whereas they could copy the implementation themselves and use a constant for that string. This is an extreme example, but it goes to show that DTFx should be very critical of how it implements tracing.

### OpenTelemetry

[Specification](https://github.com/open-telemetry/opentelemetry-specification) - [messaging](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md) may be the most relevant document there.

[DotNet SDK](https://github.com/open-telemetry/opentelemetry-dotnet)

Example OpenTelemetry "Instrumentation" Library: [NServiceBus.Extensions.Diagnostics](https://github.com/jbogard/NServiceBus.Extensions.Diagnostics)

### ActivitySource

In .net5, a replacement for `DiagnosticSource` and `DiagnosticListener` was introduced: [ActivitySource](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource?view=net-5.0). This is backwards compatible with older .net versions - just need [System.Diagnostics.DiagnosticSource/5.0](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/5.0.1) package. DTFx can perform both modern and legacy. The design of these is that with no listeners, tracing is a no-op.

**Comment by ConnorMcMahon** [comment]
Thanks for this feedback! Adding @bachuv to see how much of this we should be tracking in our Distributed Tracing GA initiative.

**Comment by davidmrdavid** [comment]
+1, thank you so much for this feedback; really appreciated!
I had a few follow-up questions, to get some clarity, let me inline them below some of your comments.

(1) **On success and failure** 
> Request/Dependency telemetry does not include success or failure.

When you say this, do you mean that the telemetry does not include whether an activity and/or orchestration succeeded or error'ed out? 

(2) **On metadata**
> Request/Dependency telemetry does not include general metadata about the orchestration or activity executed.

This is interesting! What are some kinds of metadata you would like to see? I worry about leaking potentially private data if we're not careful about this.

(3) **On Start & Stop events**
> Does not follow proper started & stopped events.

I'm not sure what is meant here by Start and Stop events. Could you please clarify? _I suspect this is about orchestration replays but I think there's some ambiguity._

(4) **On inconsistent `System.Diagnostics.Activity.Current`**
> In some cases, such as TaskActivity execution, the diagnostics activity is always present. For orchestrations it is only present sometimes.

What are some, or at least one, of these cases where the diagnostics activity is not present? Just to make sure we can get a reproducer going.

The rest seemed pretty clear to me! Again, thank you so much for the thoughtful write-up!

**Comment by davidmrdavid** [comment]
Sorry for the accidental closing of this issue just now, that was an accident when posting my comment above.

**Comment by jviau** [comment]
> (1) **On success and failure**
> 
> > Request/Dependency telemetry does not include success or failure.
> 
> When you say this, do you mean that the telemetry does not include whether an activity and/or orchestration succeeded or error'ed out?

Exactly - the event sent to the diagnostic listener is only the `TraceContextBase` object (and its derived types). This does not contain any information about what this is for _asides_ from the operation information. Namely, there is no way to know if the orchestration or activity this event is being sent for even succeeded or if it failed. See https://github.com/Azure/durabletask/blob/main/samples/Correlation.Samples/TelemetryActivator.cs#L35. The app insights objects being constructed there have a `.Success` field. But there is no information on what to populate them with there.

> (2) **On metadata**
> 
> > Request/Dependency telemetry does not include general metadata about the orchestration or activity executed.
> 
> This is interesting! What are some kinds of metadata you would like to see? I worry about leaking potentially private data if we're not careful about this.

This is mostly just an expansion of (1) - the have success / failure telemetry. It would be nice to have general information about what was just ran. In aspnetcore, the entire `HttpContext` is included here. In an outbound web request, the `HttpRequestMessage` _and_ `HttpResponseMessage` are included (well, depends on if it is the Start or Stop event). There is no concern for private data being leaked here. This is not leaving your program here. It is up to the distributed trace system to determine what (if anything) from these context objects will be included in telemetry. If you look at open-telemetries [HTTP instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http) you can see how they include important parts of the request/response, but also don't blindly include sensitive information.

This will require a fair amount of investigation and work on DTFx here as there is a lot to understand here. Even the sending of context objects at all seems to be going away (kind of), and instead `ActivitySource` is used, which sends the `Activity` object. Here it is expected that DTFx has already pre-populated the Activity with all the important information regarding what is being traced. DTFx will probably want to follow the open telemetry spec here - they have some good docs on what to include, what format to use, and how to include it. This is to give a consistent distributed tracing experience across many services.

> (3) **On Start & Stop events**
> 
> > Does not follow proper started & stopped events.
> 
> I'm not sure what is meant here by Start and Stop events. Could you please clarify? _I suspect this is about orchestration replays but I think there's some ambiguity._

This is in regards to _how_ distributed tracing events are done in C#. Simply put, its just the standard. And it would be _very_ nice if DTFx followed the standard and was consistent with other distributed tracing implementations. The part of the standard I am talking about here is every distributed tracing event should have **two** events associated with it. The "Start" event, and the "Stop" event. So if we talk about DTFx requests, then the "Start" event would be done _before_ the orchestration is first ran, and the stop event is done _after_ the orchestration has finished. As I mentioned though, this will be complicated for DTFx though with how the "start" and "stop" of an orchestration is disjointed due to the way it is replayed to and from the queue multiple times.

> (4) **On inconsistent `System.Diagnostics.Activity.Current`**
> 
> > In some cases, such as TaskActivity execution, the diagnostics activity is always present. For orchestrations it is only present sometimes.
> 
> What are some, or at least one, of these cases where the diagnostics activity is not present? Just to make sure we can get a reproducer going.

This is simple to reproduce. In any orchestration, `Activity.Current` is **only** set during the first run of the orchestration. All subsequent replays it is null.

> The rest seemed pretty clear to me! Again, thank you so much for the thoughtful write-up!

No problem! Happy to help. Feel free to ping me on teams also if you need.

I just want to re-iterate, that my goal here is to get DTFx distributed tracing to follow the open telemetry spec and be as consistent with other C# implementations as possible. This will drastically simplify hooking up DTFx distributed tracing. Ideally, when done correctly it should be a single line when configuring the open telemetry SDK - like how it is with many other open telemetry instrumentation libraries. And then it will not just be limited to application insights, but support any distributed tracing system that open telemetry supports. And with proper use of diagnostic `ActivitySource` and `Activity`, it won't even be limited to open telemetry.

**Comment by cgillum** [comment]
@jviau and @bachuv are we good to close this now that some of the new distributed tracing feature work has been merged?

**Comment by jviau** [comment]
Yeah, this is addressed now.
