### ISSUE TITLE
Exception thrown in TaskActivity is not properly propagated to retry Handle

### ISSUE THREAD

**Issue by grzesiekbugajski** [Azure/durabletask#604]
TaskFailedException does not include details about the original exception.
Without original exception, it is hard to write a proper retry logic used in ScheduleWithRetry method.

**Orchestrator**
```  
var retryOptions = new RetryOptions(DefaultFirstRetryInterval, DefaultNumberOfRetries)
            {
                Handle = (e) =>
                {
                    return true;
                },
                // Back-off: 10s, 27s, 1m, 2m, 3m, 6m, 10m, 16m, 28m, 1h
                BackoffCoefficient = 1.7d
            };

await context.ScheduleWithRetry<bool>(typeof(TestTaskActivity), retryOptions, parameters);
```
**Activity**
```
    public class TestTaskActivity : AsyncTaskActivity<TestOrchestrationInput, bool>
    {
        protected override Task<bool> ExecuteAsync(TaskContext context, TestOrchestrationInput input)
        {
            throw new TimeoutException();
        }
    }
```
**Exception**
![retry (2)](https://user-images.githubusercontent.com/75392780/132381864-ea94609c-4cff-47fe-90d0-036fd43cde9d.png)

**Expected Behavior**
InnerException of TaskFailedException should be set to an exception that was thrown in activity.

**Comment by jviau** [comment]
Hi @grzesiekbugajski, I believe you need to set a flag on your `TaskHubWorker` dispatchers `IncludeDetails`.

``` CSharp
worker.TaskActivityDispatcher.IncludeDetails = true;
worker.TaskOrchestrationDispatcher.IncludeDetails = true;
```
