### ISSUE TITLE
WaitForOrchestrationAsync gets stuck in Running even though it finished?

### ISSUE THREAD

**Issue by petertiedemann** [Azure/durabletask#619]
Hi. I am trying to evaluate DTF to replace an in-house distributed task implementation, and while its looking great, I am having what seems to be a fairly fundamental issue (**so probably I am doing something wrong** ;). 

What I am seeing is that orchestrations  execute just fine, but stay stuck in "Running" state. I have included a small example below. In this particular example, the "Done waiting" message is printed, but WaitForOrchestrationAsync never ends (and if I change the code to poll the state, it stays in "Running". If I remove the await inside the orchestration it works fine but that is kind of the whole point of DTF :)

This simple example is derived from a bigger example with the same problems (where the orchestration is only await'ing scheduled tasks).

```cs
var service = new LocalOrchestrationService();
await service.CreateIfNotExistsAsync();
await service.StartAsync();

var worker = new TaskHubWorker(service);
worker.AddTaskOrchestrations(typeof(UpperCaseOrchestrator));
await worker.StartAsync();

var client = new TaskHubClient(service);
var instance = await client.CreateOrchestrationInstanceAsync(typeof(UpperCaseOrchestrator), "hello world");
    
var state = await client.WaitForOrchestrationAsync(instance, TimeSpan.FromMilliseconds(100000));
Console.WriteLine($"Output: {state.Output}");

await worker.StopAsync(true);

public class UpperCaseOrchestrator : TaskOrchestration<string, string>
{
    public override async Task<string> RunTask(OrchestrationContext context, string input)
    {
        Console.WriteLine($"Input: {input}");
        await Task.Delay(100).ConfigureAwait(false);
        Console.WriteLine($"Done waiting");

        return input.ToUpperInvariant();
    }
}
```

My csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Azure.DurableTask.Emulator" Version="2.5.4" />
      <PackageReference Include="Microsoft.Azure.DurableTask.Core" Version="2.5.6" />
    </ItemGroup>

</Project>
```
(I am using .net 6.0 rc1 here, but in the bigger project I am using netcoreapp3.1)

Hope something can point me in the right direction :) 

EDIT: Whether ConfigureAwait is used in the orchestration does not make any difference.

**Comment by cgillum** [comment]
Hi @petertiedemann. This is happening because of your call to `await Task.Delay` call in the orchestrator code. Orchestrations must not await any task except for Durable tasks generated by the context object. Otherwise the scheduler gets confused and things like this will happen. If you need to delay, you should instead use `context.CreateTimer` or delay inside an activity task.

**Comment by petertiedemann** [comment]
@cgillum Thanks for the quick response. In the more complex example I have do no await non-durable tasks, but I am still seeing the same behavior ( or rather, I was, but I removed that ).

The pattern there is (modified from actual code in RunTask): 
```cs
      var jobs = definition.Input.Select(
          id=>
            context.ScheduleTask<string>(
              typeof(MyTask),
              new MyTaskInput(...) ) )
        .ToList();

      var secondaryTask =
        context.ScheduleTask<string>(
          typeof(MyOtherTask),
          new MyOtherTaskInput(...) );
      
      await Task.WhenAll( jobs ).ConfigureAwait( false );
      await secondaryTask .ConfigureAwait( false );

      return  ...;
```
Again, here I am seeing the return being reached, but the orchestation keeps running.

I assume that in TaskActivities I am allowed to use normal await, right?

**Comment by petertiedemann** [comment]
Thanks. I am just so used to writing ConfigureAwait(false) that i don't even think about it :)

Looking forward to continuing trying this out, the ability to work with remote long running tasks using async await is really nice.
