### ISSUE TITLE
Dependency on unsigned ImpromptuInterface NuGet package

### ISSUE THREAD

**Issue by older** [Azure/durabletask#645]
I understand that `ImpromptuInterface` provides valuable features, but this dependency makes it hard to use Azure Durable Functions in a strict environment where only trusted packages are allowed. This package is not owned by Microsoft/Azure/.NET Foundation and not signed by the author.
Maybe it would be possible to just include relevant sources from that project into repository (submodule maybe) instead of referencing it from NuGet?

**Comment by cgillum** [comment]
Thanks for bringing this to our attention. It looks like the [ImpromptuInterface](https://github.com/ekonbenefits/impromptu-interface) project is no longer receiving any commits. Given that both projects are under the Apache 2.0 license, it should be straight-forward to just take a source dependency, especially if the code can be taken unmodified.

**Comment by aueloka** [comment]
Perhaps this issue can be closed since the dependency on ImpromptuInterface was removed as part of [this](https://github.com/Azure/durabletask/commit/48a85464a9944be9b6b58875f1ea9fb700bbeda5) commit?

**Comment by cgillum** [comment]
Yes! The next release of DurableTask.Core (v2.11.0) will no longer have ImpromptuInterface as a dependency (thanks @aueloka)!
