### ISSUE TITLE
Cross partition background synchronization instance queries + increased Azure Table Storage latency

### ISSUE THREAD

**Issue by brrusino** [Azure/durabletask#654]
Hello all,

recently we saw a pronounced spike in latency for our Azure Table Storage queries, up to ~2.5s on average from our previous average of ~30ms.

On investigating the actual queries during this increase in latency, they seem to be cross-partition:
https://stchaostcs5rgc4ozxqru6.table.core.windows.net:443/ARGSYNCWORKERHUBInstances?$filter=PartitionKey%20eq%20%27a4a4123668be478988165ec6556c1d22%27%20or%20PartitionKey%20eq%20%27d394c8e640634d5d8c82c78e6d0c22f6%27%20or%20PartitionKey%20eq%20%27e29e71441cc44372b9acac455444cfd5%27%20or%20PartitionKey%20eq%20%27c21e0b8c04b9427581e87be0a5e22560%27%20or%20PartitionKey%20eq%20%279943e366941e47e49b3800b3879de696%27%20or%20PartitionKey%20eq%20%278d9c5e371b004d52a77da1196cd6acb9%27%20or%20PartitionKey%20eq%20%27abcf8483e020446099c381da8a655024%27%20or%20PartitionKey%20eq%20%27c3c87167985143de99445e78bb0e8d04%27%20or%20PartitionKey%20eq%20%2788a47df3a0044d8eaa6a0b7a9dade538%27%20or%20PartitionKey%20eq%20%2724d42a7b39bd435d8e6009b66756bf2e%27%20or%20PartitionKey%20eq%20%27c022b8a6b116490f8974d911e3da8a67%27&$select=ExecutionId%2CCreatedTime%2CPartitionKey%2CRowKey%2CTimestamp

For our own clarity/understanding, is this cross-partition behavior indicative of multiple concurrent orchestrator functions executing on the given worker instance? Just attempting to better understand the underlying behavior that creates these cross-partition synchronization queries (and the associated increase in latency).

Thanks,
Brent

**Comment by cgillum** [comment]
This was a regression that was introduced in an earlier version of the DurableTask.AzureStorage nuget package. I suspect you're running an older version of this package. If you upgrade to the latest version (currently [v1.10.0](https://github.com/Azure/durabletask/releases/tag/durabletask.azurestorage-v1.10.0)), you should no longer see these high-latency cross-partition table queries in the runtime.

**Comment by brrusino** [comment]
Our service is currently using Microsoft.Azure.WebJobs.Extensions.DurableTask v2.6.0, which requires a minimum version of DurableTask.AzureStorage of v1.9.4. Is there something else that might be off?

**Comment by cgillum** [comment]
The issue should have been fixed in the [v1.8.8](https://github.com/Azure/durabletask/releases/tag/durabletask.azurestorage-v1.8.8) release, so I'm surprised that you're seeing this in v1.9.4. Since you're using Durable Functions, I may be able to look at the internal service telemetry to confirm which version you're using and whether these queries are being issued.

**Comment by brrusino** [comment]
Discussed offline, will be adding DurableTask.AzureStorage logging to our service (currently seeing these in live logs but not our internal telemetry via AppInsights). Is there documentation for how to enable this outside of Durable Functions use of host.json?

**Comment by brrusino** [comment]
Ok, was able to track back through recent changes to this service and it looks like we recently updated `Microsoft.Azure.WebJobs.Extensions.DurableTask` from v2.5.0 to v2.6.0, which would have taken `DurableTask.AzureStorage` from v1.8.6 (likely before the fix) to v1.9.4. This update deploying to the observed region lines up with the return to more reasonable latency values. @cgillum, to confirm (and potentially close this issue) - was `DurableTask.AzureStorage` v1.8.6 a version affected by the regression?

**Comment by cgillum** [comment]
Yes, this issue was first introduced as part of [this PR](https://github.com/Azure/durabletask/pull/528) which went out with [v1.8.6](https://github.com/Azure/durabletask/releases/tag/durabletask.azurestorage-v1.8.6).

**Comment by brrusino** [comment]
Thanks @cgillum, in that case I'll mark this closed - appreciate the help.
