### ISSUE TITLE
Message added to Azure Storage Control queue is created with TTL of 7 days by default

### ISSUE THREAD

**Issue by inuvano-labs** [Azure/durabletask#660]
As `null` is passed for the param `timeToLive`:

https://github.com/Azure/durabletask/blob/859311cfc2223eda9404448c7ef9587518988d13/src/DurableTask.AzureStorage/Storage/Queue.cs#L46-L59

In `Microsoft.Azure.Storage.Queue` this results in the `initialVisibilityDelayInSeconds` var never being set:
https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Queue/CloudQueue.cs#L2472-L2524

```csharp
        private RESTCommand<NullType> AddMessageImpl(CloudQueueMessage message, TimeSpan? timeToLive, TimeSpan? initialVisibilityDelay, QueueRequestOptions options)
        {
            long? timeToLiveInSeconds = null;
            int? initialVisibilityDelayInSeconds = null;


            if (timeToLive.HasValue)
            {
                if (timeToLive.Value.Equals(TimeSpan.FromSeconds(-1)) || timeToLive.Value > TimeSpan.Zero)
                {
                    timeToLiveInSeconds = (long)timeToLive.Value.TotalSeconds;
                }
                else
                {
                    throw new ArgumentOutOfRangeException("timeToLive", string.Format(CultureInfo.InvariantCulture, SR.ArgumentOutOfRangeError, timeToLive));
                }
            }
            ...
```
Then the internal REST call is made, but due to the `timeToLiveInSeconds` param being null - it's never added to the body of the request. 
https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Queue/Protocol/QueueHttpRequestMessageFactory.cs#L187-L203
```csharp
        public static StorageRequestMessage AddMessage(Uri uri, int? timeout, long? timeToLiveInSeconds, int? visibilityTimeoutInSeconds, HttpContent content, OperationContext operationContext, ICanonicalizer canonicalizer, StorageCredentials credentials)
        {
            UriQueryBuilder builder = new UriQueryBuilder();


            if (timeToLiveInSeconds != null)
            {
                builder.Add(Constants.QueryConstants.MessageTimeToLive, timeToLiveInSeconds.Value.ToString());
            }


            if (visibilityTimeoutInSeconds != null)
            {
                builder.Add(Constants.QueryConstants.VisibilityTimeout, visibilityTimeoutInSeconds.Value.ToString());
            }


            StorageRequestMessage request = HttpRequestMessageFactory.CreateRequestMessage(HttpMethod.Post, uri, timeout, builder, content, operationContext, canonicalizer, credentials);
            return request;
        }
```
Therefore, resulting in the storage REST API defaulting to 7 days, as per the documentation:
https://docs.microsoft.com/en-us/rest/api/storageservices/put-message

messagettl=<int-seconds> | Optional. Specifies the time-to-live interval for the message, in seconds. Prior to version 2017-07-29, the maximum time-to-live allowed is 7 days. For version 2017-07-29 or later, the maximum time-to-live can be any positive number, as well as -1 indicating that the message does not expire. **If this parameter is omitted, the default time-to-live is 7 days.**

Are there any implications passing `TimeSpan.FromSeconds(-1)` as the `timeToLive` instead of `null`? The unit tests seem to still pass...:
https://github.com/Azure/durabletask/blob/859311cfc2223eda9404448c7ef9587518988d13/src/DurableTask.AzureStorage/Storage/Queue.cs#L46-L59

We were caught out by this on return from the holidays, whereby our dev environment was shutdown (durable functions on AKS). All our eternal orchestrations (1000s) that where awaiting `IDurableOrchestrationContext.CreateTimer` became corrupted due to the underlying message being deleted as it had lapsed 7 days. 

We had to terminate all the orchestrations and re-create them as they were stuck with a `Running` status.

**Comment by cgillum** [comment]
@amdeel this might be a good issue for you to take a look at since you've been doing a lot of work on the Azure Storage backend lately.

I think the only thing that _might_ prevent us from doing this is the fact that we're still using a really old version of the .NET Storage SDK (v9.3.3). However, I haven't checked to see what REST version this nuget package corresponds to. It would be great if we could provide an infinite TTL for queue messages in the current version, if possible. Either way, I think we definitely want to use infinite TTLs to avoid this kind of stuck orchestration issue.
