### ISSUE TITLE
What does `DequeueCount` stands for in `[dt].[Tasks]` of SQL Provider

### ISSUE THREAD

**Issue by jundayin** [Azure/durabletask#672]
Hi, 

Recently we observed a task schedule in database takes too long to be pick up by the worker (10 minutes). We thought it is about exception and retry but we didn't see any logs indicating the exception. We only found `DequeueCount` of this task kept incrementing and it got handled by the worker eventually.  Please note there is only one task in the `[dt].[Tasks]` table at the moment

The duration between the task was queued and executing started is totally random. It can be picked up immediately after the task is queued but it can also stuck nearly 5~10 minutes to execute.  Now I want to know what does the `DequeueCount` stand for and would like to ask from the the DTF's dev what can we do to investigate the cause of this random delay

```
InstanceID	                        ExecutionID	                        SequenceNumber	EventType	        TaskID	Timestamp	 
97d4ba3f9d2947fba26c7e1c864e8f3d:0	804700e0698f4ed1955bd224eacd5f9b	14	        TaskScheduled	        3	2022-01-28 12:03:01.3799932
97d4ba3f9d2947fba26c7e1c864e8f3d:0	804700e0698f4ed1955bd224eacd5f9b	15	        OrchestratorCompleted	NULL	2022-01-28 12:03:01.3799969
97d4ba3f9d2947fba26c7e1c864e8f3d:0	804700e0698f4ed1955bd224eacd5f9b	16	        OrchestratorStarted	NULL	2022-01-28 12:13:10.4266115
97d4ba3f9d2947fba26c7e1c864e8f3d:0	804700e0698f4ed1955bd224eacd5f9b	17	        TaskCompleted           3	2022-01-28 12:13:10.3801942
```

**Comment by jundayin** [comment]
Would like to hear input from @cgillum

**Comment by cgillum** [comment]
The DequeueCount column indicates how many times we tried to process the work-item. If it ever goes above 1, most likely some problem is occurring that prevents it from being successfully processed. For example, if the work-item results in a process crash, then you will see this number increase. Less severe errors in execution can also cause this behavior, but in those cases I would expect you to be able to see warnings or errors in the logs. To investigate further, make sure you are properly capturing logs from the `DurableTask.SqlServer` source and make sure you are tracking process IDs or doing whatever makes sense in your environment to detect process recycling.

**Comment by jundayin** [comment]
Do we have documentation regarding how to setup the logs of SQL Server Provider? We have logs for business logic running orchestration but that doesn't reveal us much about the retry.

**Comment by cgillum** [comment]
Yes, we have it in the [quickstart documentation](https://microsoft.github.io/durabletask-mssql/#/quickstart), though it's admittedly not easy to find. We're hoping to improve the structure of the documentation soon.

You can also find general documentation, including code samples, for capturing logs here: https://github.com/Azure/durabletask/tree/main/src/DurableTask.Core/Logging#readme
