### ISSUE TITLE
Urgent Issue - How to delete/disable schedule orchestrations

### ISSUE THREAD

**Issue by vedsinghal** [Azure/durabletask#677]
**Schedule Orchestration**

We are facing an issue in deleting/disabling schedule orchestration which is causing a risk in our production environment. 

An on-going orchestration is getting terminated successfully but the one which got scheduled and not triggered yet is creating this problem. 

Appreciate your help on this issue.

Thanks in advance.

**Comment by cgillum** [comment]
You’re trying to cancel an orchestration that is scheduled for a future time? What orchestration service type are you using? Service Bus? Azure Storage? The only way to cancel a scheduled orchestration is to somehow delete the scheduled message from the queue, but there may not be a way to do this safely that doesn’t impact other orchestrations.

**Comment by vedsinghal** [comment]
Thanks Chris for your prompt response. Here are the relies to your questions :

**Q**. You’re trying to cancel an orchestration that is scheduled for a future time? 
**A**. Yes I am trying to cancel the one that is scheduled for a future time.

**Q**. What orchestration service type are you using? Service Bus? Azure Storage?
**A**. I am using Azure storage orchestration service type.

**Q**. The only way to cancel a scheduled orchestration is to somehow delete the scheduled message from the queue, but there may not be a way to do this safely that doesn’t impact other orchestrations.
**A**. Not sure if this is applicable for Azure storage orchestration service type?

**Comment by cgillum** [comment]
I'm afraid that we don't have any built-in way to safely cancel a scheduled orchestration when using the Azure Storage orchestration service type.
