### ISSUE TITLE
Question: Specialized workers

### ISSUE THREAD

**Issue by petertiedemann** [Azure/durabletask#682]
We are experiment with the durable task framework and really liking what we see so far. I do have a bit of trouble understanding what configuration of workers are allowed.

Say I have a TaskOrchestration A that uses TaskActivities B and C.

1. Is it allowed to have a worker that only knows about B?
2. Is it allowed to have a worker that only knows about A and B?
3. Assume that we add a TaskOrchestration A2 that uses TaskActivity B2, am I then allowed one worker that knows A,B,C and another worker that knows A2, B2?

From a bit of experimentation it definitely seems 1 and 2 are _not_ allowed? I assume 3 _is_ allowed?

**Comment by cgillum** [comment]
Glad to hear you're liking what you see so far. :)

> Is it allowed to have a worker that only knows about B?

Unfortunately no, not today. All dependent orchestrations and activities have to be registered on the same worker.

> Is it allowed to have a worker that only knows about A and B?

It sounds like this is a variation on the previous question. Hopefully my previous answer clarifies this.

> Assume that we add a TaskOrchestration A2 that uses TaskActivity B2, am I then allowed one worker that knows A,B,C and another worker that knows A2, B2?

Yes, this is perfectly fine.

**Comment by petertiedemann** [comment]
Thank you for *extremely* fast reply! And yes, 2 was a variation of 1, I only asked because I thought maybe it was okay to only know one task as long the worker knew the "root" orchestration.
