### ISSUE TITLE
After invoking the WaitForOrchestrationAsync the Completed status is too early.

### ISSUE THREAD

**Issue by DanielGigante12345** [Azure/durabletask#695]
I have created a Worker Service to process 5000 workflows as follow:

1. create 5000 orchestrations with the "CreateOrchestrationInstanceAsync" method
2. simulate the completion of the workflows by completing all the workflows at the same time
3. get the orchestrations state of the 5000 completed workflows

The issue is that once all workflows are completed the TaskHubWorker is not waiting for the method WaitForOrchestrationAsync to complete before updating the status of the SQL table "Instance". Two or even three thousands records are being updated in a brief time and the remaining workflows seems to be updated correctly one at the time.

I noticed this issue because I am updating a second table after calling the WaitForOrchestrationAsync  method and that table is being updated correctly one record at the time.

The logic of the application is:

1. The "Worker.cs" calls the "TaskWorkflowRequestHolidays.cs"
2. The "TaskWorkflowRequestHolidays.cs" retrieves records from a SQL db (5000 records) and through the "Task.Run" invokes the "WkfRequestHolidaysOrchestrator.cs" for each of the records.
3. The "WkfRequestHolidaysOrchestrator.cs" creates the orchestrations with the "CreateOrchestrationInstanceAsync" method on the first round trip and on the second round trip calls the "WaitForOrchestrationAsync" method to retrieve their states.

Thanks in advance for your advise.

[WorkflowEngine.zip](https://github.com/Azure/durabletask/files/8287104/WorkflowEngine.zip)

**Comment by cgillum** [comment]
I'm having trouble understanding the problem description. Can you share an example of some relevant code? The WorkflowEngine.zip link returns 404.

**Comment by DanielGigante12345** [comment]
In the first round I create 5000 orchestrations with the "CreateOrchestrationInstanceAsync" method and then in a second round I wait for those 5000 orchestrations with the "WaitForOrchestrationAsync" method.

All 4 activities are triggered but before all activities are completed, a lot of times, the column "RuntimeStatus" of the SQL table "Instance" is being updated as "Completed" even if not all activities are completed.

                    await taskHubClient.WaitForOrchestrationAsync(instance, TimeSpan.FromDays(30), CancellationToken.None);
                    var result = await taskHubClient.GetOrchestrationStateAsync(instance);

                    model = _db.GetUserHolidaysByIDSynch(model);
                    model.DurableStatus = result.OrchestrationStatus.ToString();
                    model.DateWorkflowCompleted = DateTime.Now;
                   _db.UpdateUserHolidaysRequestSynch(model);

The "GetOrchestrationStateAsync" method is telling me that the "RuntimeStatus = Completed" so I update my own SQL table but the problem is that not all activities are really completed so it is giving me erroneous information.



[WorkflowEngine_22032022.zip](https://github.com/Azure/durabletask/files/8322305/WorkflowEngine_22032022.zip)

**Comment by DanielGigante12345** [comment]
I have done as suggested creating a single shared "taskhubworker" for all the orchestrations and activities and the anomaly didn't happen again. Thanks and please close the issue.

**Comment by DanielGigante12345** [comment]
I have tried as suggested and you can find the code attached.
The issue keeps happening.

In the page "WkfRequestHolidaysOrchestrator.cs" as show in the PNG image, I have 2000 workflows that have completed all their activities and I have 2000 threads that are waiting for the "WaitForOrchestrationAsync" to execute.

When all activities are finished the "RuntimeStatus" field of the "Instances" table for all 2000 workflows is almost immediately updated to "Completed" but each of the thread is still being processes by the next "GetOrchestrationStateAsync" statement and my SQL table is being updated one at the time.

So basically what I mean is that the  the "RuntimeStatus" field of the "Instances" table is immedialtely updated even though not all the 2000 threads have gone through the "GetOrchestrationStateAsync" and my table update. It takes a few seconds to update the "RuntimeStatus" field of the "Instances" table while it takes a few minutes to execute the "GetOrchestrationStateAsync" and my table update.

![image](https://user-images.githubusercontent.com/101813547/165492553-22064019-43fb-4601-bd3e-3f891d202533.png)


[Liebherr Workflow Engine_27042022.zip](https://github.com/Azure/durabletask/files/8570944/Liebherr.Workflow.Engine_27042022.zip)

**Comment by DanielGigante12345** [comment]
One more issue. I have updated to the "Microsoft.DurableTask.SqlServer (1.0.0-rc)"
![image](https://user-images.githubusercontent.com/101813547/165498120-b290c2f5-efcb-468d-a0d8-7cc3724e35f8.png)

Calling the method "CreateOrchestrationInstanceAsync" is ok but the call to the method "WaitForOrchestrationAsync" raises the error: "ParentInstanceID"

Stack trace:

   at Microsoft.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at Microsoft.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at DurableTask.SqlServer.SqlUtils.GetParentInstanceId(DbDataReader reader)
   at DurableTask.SqlServer.SqlUtils.GetOrchestrationState(DbDataReader reader)
   at DurableTask.SqlServer.SqlOrchestrationService.<GetOrchestrationStateAsync>d__30.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at DurableTask.SqlServer.SqlOrchestrationService.<WaitForOrchestrationAsync>d__28.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at liebherr.workflow.durable.Orchestrations.WkfRequestHolidays.WkfRequestHolidaysOrchestrator.<WkfRequestHolidayCreateOrchestrator>d__42.MoveNext() in E:\lmbgid0_sources\NEW_liebherr.net.workflow\liebherr.workflow.durable\Orchestrations\WkfRequestHolidays\WkfRequestHolidaysOrchestrator.cs:line 67

**Comment by DanielGigante12345** [comment]
I have added now everything needed to simulate the issue.

1. 	liebherr_workflows_db.sql -> script to create the db (including the durable table)
2.	export_2000_rows.sql -> 2000 records to simulate
3.	the code to execute the Windows Service (worker)

[Liebherr Workflow Engine.zip](https://github.com/Azure/durabletask/files/8571769/Liebherr.Workflow.Engine.zip)

Once all setup, execute the Worker then wait for the following query to return a result of 2000:

select count(*) as WKFL_MANAGER_APPROVAL_URL FROM [Liebherr.WorkFlowsDB].[dbo].[WkfRequestHolidays] with (nolock) where ManagerApprovalURL is not null
go

Then execute the following queries:

update [Liebherr.WorkFlowsDB].[dbo].[WkfRequestHolidays] set ManagerApproved = 1 where ManagerApprovalURL is not null
go
update [Liebherr.WorkFlowsDB].[dbo].[ApprovalsOrchestrator] set ActivityApproved = 1 where ApprovalType = 'Manager'
go

Wait again for the following query to return a result of 2000:

select count(*) as WKFL_HAL_APPROVAL_URL FROM [Liebherr.WorkFlowsDB].[dbo].[WkfRequestHolidays] with (nolock) where HALApprovalURL is not null
go

Then execute the following query:

update [Liebherr.WorkFlowsDB].[dbo].[WkfRequestHolidays] set HALApproved = 1 where HALApprovalURL is not null
go
update [Liebherr.WorkFlowsDB].[dbo].[ApprovalsOrchestrator] set ActivityApproved = 1 where ApprovalType = 'HAL'
go

At this point you will need to execute the following queries:

select count(*) as DURABLE_COMPLETED FROM [Liebherr.WorkFlowsDB].[dt].[Instances] where RuntimeStatus = 'Completed'
go
select count(*) as WKFL_COMPLETED FROM [Liebherr.WorkFlowsDB].[dbo].[WkfRequestHolidays] with (nolock) where DurableStatus = 'Completed'
go


The first query will quickly return all 2000 records as "Completed" (there the issue) while the second query will slowly return the status "Completed" for each of the 2000 workflows.

**Comment by DanielGigante12345** [comment]
I add the 2nd project that I forgot to include for the Worker
[liebherr.workflow.durable_27042022.zip](https://github.com/Azure/durabletask/files/8571930/liebherr.workflow.durable_27042022.zip)
.

**Comment by DanielGigante12345** [comment]
Apologies. The solution is too big to attach so I added each single dependcy as ZIP file.

[liebherr.workflow.dac_27042022.zip](https://github.com/Azure/durabletask/files/8572297/liebherr.workflow.dac_27042022.zip)
[liebherr.workflow.common_27042022.zip](https://github.com/Azure/durabletask/files/8572311/liebherr.workflow.common_27042022.zip)

**Comment by DanielGigante12345** [comment]
Closing this issue. Will create new tickets with separate specific issues.
