### ISSUE TITLE
Recommendation Ask: Retrieving and passing secrets around

### ISSUE THREAD

**Issue by saguiitay** [Azure/durabletask#697]
This is a request for a recommendation

Assume my orchestration needs to do some work with secrets - e.g. a Storage Account Key.
I'd like to retrieve the secrets (e.g. from Storage, or from a KeyVault) and then use it.

I could retrieve the key from one Activity, and then pass it to another Activity. That will guarantee retries in case of network issues, etc. However, that means that the key will be stored in the Orchestration/Activity history's storage (e.g. as a blob), which is considered unsafe.
I could retrieve the key as part of the Orchestration, but then I can't pass it to other activities (due to the above issue). I also suffer from the lack of retries in case of failures.

Is there any recommendations here?

**Comment by cgillum** [comment]
My recommendation is that each activity fetch the secrets independently. That way you don't have to worry about secrets being persisted in history and potentially leaked. This also grants you some protection from problems related to key rotations. For example, if a key gets rotated, orchestrations that have the older key cached in history will become effectively broken. Fetching the key each time inside an activity allows you to know that you're always getting the latest key.

If you're concerned about performance, you _could_ consider caching the secret in shared (static) memory inside your activity. It's not guaranteed to always be there if your app is scaled out to multiple processes, but it should help reduce overall I/O against KeyVault or whatever key store you're relying on.

**Comment by jviau** [comment]
I have previously looked into this issue, and I surmised (but have yet to implement it), that this can be done via encrypting / decrypting inputs to an Orchestration or Activity. There is even a package that help with just this! [Microsoft.AspnNetCore.DataProtection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-6.0). It has `AspNetCore` in the name, but it actually has no dependency on `AspNetCore`, so it is safe to use in DTFx (however, it does bring in Microsoft.Extensions ecosystem).

My plan when we do implement this would be to use this package and integrate it into a DI'd type, so it would simple encrypt/decrypt itself as part of JSON serialization. So now it will be encrypted on queue, but decrypted and ready to use in memory.

AzureStorage and many other orchestration services are already encrypted at rest (but anyone with read access can decrypt), so this offers an additional layer of protection.
