### ISSUE TITLE
Include request information sent by Azure storage exception.

### ISSUE THREAD

**Issue by jitinjohn** [Azure/durabletask#7]
Include additional exception information like below sent by Azure storage.

http://blogs.msdn.com/b/cie/archive/2013/05/31/microsoft-windowsazure-storage-storageexception-unexpected-response-code-for-operation.aspx

Request Information
 RequestID:fe0a42c7-faeb-4fd7-a9f8-690bc12e1f41
 RequestDate:Tue, 21 May 2013 13:48:55 GMT
 StatusMessage:Accepted
 ErrorCode:OutOfRangeInput

**Comment by cgillum** [comment]
The latest Azure Storage SDKs are currently including request information, so I'm considering this resolved.
