### ISSUE TITLE
AAD authentication prerequisites for AzureStorageOrchestrationService

### ISSUE THREAD

**Issue by rozhnovl** [Azure/durabletask#701]
Hi.
I'm trying to utilize durabletask framework in an application which runs on top of k8 and uses certificate-based AAD authentication to access Azure resources.
It's not quite clear from the documentation, what's the right way to setup storage account/initialize AzureStorageOrchestrationService to use it properly.
For now, I'm trying to initialize credential this way:
```
private const string AzureStorageScope = "https://storage.azure.com/.default";
var tc = new WindowsAzure.Storage.Auth.TokenCredential((await credential.GetTokenAsync(new TokenRequestContext(scopes: new string[] { AzureStorageScope }), CancellationToken.None)).Token);
return new WindowsAzure.Storage.Auth.StorageCredentials(tc);
```
It fails with error
```
This request is not authorized to perform this operation using this permission.
DurableTask.AzureStorage
   at DurableTask.AzureStorage.Storage.AzureStorageClient.<MakeStorageRequest>d__33`1.MoveNext()
   at DurableTask.AzureStorage.Storage.Blob.<ExistsAsync>d__12.MoveNext()
   at DurableTask.AzureStorage.Partitioning.BlobLeaseManager.<GetTaskHubInfoAsync>d__27.MoveNext()
   at DurableTask.AzureStorage.Partitioning.BlobLeaseManager.<GetOrCreateTaskHubInfoAsync>d__24.MoveNext()
   at DurableTask.AzureStorage.Partitioning.BlobLeaseManager.<CreateLeaseStoreIfNotExistsAsync>d__13.MoveNext()
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.<GetTaskHubCreatorTask>d__52.MoveNext()
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.<EnsureTaskHubAsync>d__51.MoveNext()
```

Am I missing some documentation part where sample of using AAD authentication to connect to Azure Storage is described? Should some other scope be used, or specific access role needs to be assigned?

**Comment by cgillum** [comment]
@Fulborg we don't have documentation for this specifically. I suggest consulting with Azure Storage SDK documentation if you're able to find some that covers using `WindowsAzure.Storage.Auth.StorageCredentials`.  You may also want to confirm if this is a K8s specific problem or if it also doesn't work on other platforms. You mentioned certificate-based authentication specifically and I'm unfortunately not familiar enough to say what might be involved for this.

**Comment by Fulborg** [comment]
That's not a k8 problem, it occurs during development running on a local machine as a Console application
I see then, thanks, I'll continue investigating it further and make a PR to the wiki page when I figure it out. Just wanted to make sure I didn't miss anything.

**Comment by cgillum** [comment]
Adding @wsugarman in case he has any ideas or suggestions too.

**Comment by rozhnovl** [comment]
Sorry, I've figured it out. I was giving access to the wrong Service Principal. It's working just fine now, I'll document how it should be done and make a PR to add this info to the repository wiki.
