### ISSUE TITLE
What constitutes "large" history?

### ISSUE THREAD

**Issue by IGx89** [Azure/durabletask#719]
Hello! I'm designing a solution using DTFx and trying to decide whether or not to use the eternal orchestration pattern for a particular orchestrator. The documentation says to use eternal orchestrations to avoid the history getting critically large, but doesn't define what could constitute a large history.

In my scenario, I have an orchestrator that would be creating an activity once per minute over the course of an hour or two. Would that create enough history to be considered large and worthy of using the eternal orchestration pattern? Inputs/outputs will be very small, and at max scale there'd be ~1000 instances per day. It would work either way, however avoiding that pattern would allow me to make it more robust. I'll likely be using the SQL provider and be purging completed instances after a week or two, in case that helps.

Thanks for your time!

**Comment by cgillum** [comment]
I assume you're referring to "[Eternal Orchestrations](https://github.com/Azure/durabletask/wiki/Feature---Eternal-Orchestrations-%28aka-infinite-loops%29)"?

It sounds like the number of activities would be fairly bounded. If we're talking about one activity per minute over an hour or two (120 activities) and the inputs/outputs are small, then you don't have to worry about history size. It's when you get into the thousands or if you're dealing with large inputs/outputs that this becomes more of a problem. Note that sub-orchestrations are a way to keep history size under control as well, and don't require you to model your orchestrator as a loop, making it a convenient alternative in some cases.

**Comment by IGx89** [comment]
Doh, yes! Sorry about that, I've corrected the issue description. Ironically this happened right after realizing I named an Azure resource `orchestator` as well 🤦‍♂️.

That's very helpful, thanks a lot!
