### ISSUE TITLE
AzureStorageOrchestrationServiceSettings with managed identity instead of Account Key

### ISSUE THREAD

**Issue by mauve** [Azure/durabletask#741]
Hi,

Is it possible to configure the Azure Storage backend to use Managed Identity instead of ConnectionString/AccountKey?

Kind regards

**Comment by cgillum** [comment]
Yes, it is. You can use the `AzureStorageOrchestrationServiceSettings.StorageAccountDetails` property to provide connection info using managed identity credentials.

Here's an example of how we do this in Durable Functions: https://github.com/Azure/azure-functions-durable-extension/blob/752de5084001d5e100b490897dd26976fddd3233/src/WebJobs.Extensions.DurableTask/AzureStorageAccountProvider.cs#L35-L61

**Comment by mauve** [comment]
thanks @cgillum.

Is it possible to use `DefaultAzureCredential` (or any of the credentials from `Azure.Identity`) or do we need to implement our own `AzureCredentialFactory` (see https://github.com/Azure/azure-functions-durable-extension/blob/752de5084001d5e100b490897dd26976fddd3233/src/WebJobs.Extensions.DurableTask/Auth/AzureCredentialFactory.cs)

**Comment by cgillum** [comment]
The version of the storage SDK we're currently using predates Azure.Identity so I'm not sure if it can be used directly, but maybe @wsugarman has ideas?

**Comment by wsugarman** [comment]
@cgillum is right. You cannot use `Azure.Identity` out-of-the-box today. You can use the older [`Microsoft.Azure.Services.AppAuthentication`](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/) package, or you can do what we did in Azure Durable Functions where we wrap access tokens from `Azure.Identity` in the older `Microsoft.WindowsAzure.Storage.Auth.TokenCredential` class.
