### ISSUE TITLE
Support of Task.Run()

### ISSUE THREAD

**Issue by michaelshikh07** [Azure/durabletask#762]
Is it there any limitation to run a durable task, wrapped with Task.Run()?
consider the following scenario

someTaskList.Add(
                        Task.Run(async () =>
                            {
                                try
                                {
                                    await durableTask(........)
                                }
                                catch (Exception e)
                                {
                                   \\do something with exception
                                }
                            }
                        ));
 await Task.WhenAll(someTaskList);

**Comment by cgillum** [comment]
Using `Task.Run(...)` in an orchestration should generally be considered forbidden because of how it tries to queue work on the thread pool. Why would you need to do this? I would expect there is some other way to express what you need without using `Task.Run(...)`.

**Comment by michaelshikh07** [comment]
Thanks Chris,
I had a concern this might be problematic, wanted to double check it.
I will implement my code without using Task.Run().

**Comment by cgillum** [comment]
Sounds good!
