### ISSUE TITLE
Retrieving worker statistics

### ISSUE THREAD

**Issue by saguiitay** [Azure/durabletask#765]
Is there a way to retrieve hub and worker statistics?
I'd like to gather information (by hub and/or by worker), such as:

* Number of pending orchestrations
* Number of pending activities
* Number of running orchestrations
* Number of running activities
* Optional: Average wait time in queues
* etc.

This will help understand the load on the system. Along with CPU usage, I'll be able to tweak settings such as MaxConcurrentTaskOrchestrationWorkItems and MaxConcurrentTaskActivityWorkItems, or decide to scale out my cluster.

**Comment by cgillum** [comment]
Some of this information can be gathered from the logs. In particular, the following log events may be helpful:

### DurableTask.Core
* [FetchWorkItemStarting](https://github.com/Azure/durabletask/blob/cbb23ad1a23a0027a35949ae7e6eaa188862c2a7/src/DurableTask.Core/Logging/LogEvents.cs#L197)
* [FetchWorkItemCompleted](https://github.com/Azure/durabletask/blob/cbb23ad1a23a0027a35949ae7e6eaa188862c2a7/src/DurableTask.Core/Logging/LogEvents.cs#L243)
* [FetchingThrottled](https://github.com/Azure/durabletask/blob/cbb23ad1a23a0027a35949ae7e6eaa188862c2a7/src/DurableTask.Core/Logging/LogEvents.cs#L326)

### DurableTask.AzureStorage
* [OrchestrationServiceStats](https://github.com/Azure/durabletask/blob/cbb23ad1a23a0027a35949ae7e6eaa188862c2a7/src/DurableTask.AzureStorage/Logging/LogEvents.cs#L880)

DurableTask.AzureStorage also has some classes you can use to manually collect metrics in code. In particular, [DisconnectedPerformanceMonitor.PulseAsync()](https://github.com/Azure/durabletask/blob/cbb23ad1a23a0027a35949ae7e6eaa188862c2a7/src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs#L136). This is what we use for automatic scaling for Azure Functions workloads.
