### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by mzahor** [Azure/durabletask#78]
Trying to run unit tests and getting a lot of errors:

![image](https://cloud.githubusercontent.com/assets/803142/24151329/211951d6-0e51-11e7-8cfd-81a1ad3c8e4b.png)

Most of them are `409 Conflict` errors from Azure storage. Tried with several different storage accounts, same results.

Looks like in unit tests we don't wait for table deletion operation to be finished:

![image](https://cloud.githubusercontent.com/assets/803142/24151810/7638468a-0e52-11e7-9b7c-6c8b55be561b.png)

**Comment by babrekel** [comment]
Noticed the same running against real Azure Storage instances. I did not experience this issue in the storage emulator, that may unblock you for now!

**Comment by simonporter** [comment]
The tests create, destroy the same storage resources over and over, faster than is allowed for a real storage account so the storage emulator is the best way to test.

**Comment by mzahor** [comment]
ok, got it. thanks.
