### ISSUE TITLE
Support for PurgeHistoryAsync in AzureTableTrackingStore

### ISSUE THREAD

**Issue by chrissmiller** [Azure/durabletask#799]
Hi,

We are attempting to consume the PurgeHistory functionality for task hubs backed by Azure Storage. We are currently blocked because it seems that purging is not supported for AzureTableTrackingStore (https://github.com/Azure/durabletask/blob/f79aab253643e815348ae232bb9a7009c34e70ab/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs#L717). Is there any known workaround or plans to implement support here, or is support blocked for technical reasons?

Thanks!

**Comment by davidmrdavid** [comment]
routing to @amdeel, who might be able to comment.

**Comment by cgillum** [comment]
@chrissmiller I'm very confused. You're saying that purging is not supported but you provided a link to the purge code.  Can you clarify what you're actually blocked on?

**Comment by cgillum** [comment]
Oh sorry, I should have clicked the link first (I was just looking at the preview). If you scroll further down, you'll see that there are fully implemented methods for purging history: https://github.com/Azure/durabletask/blob/f79aab253643e815348ae232bb9a7009c34e70ab/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs#L759-L787

**Comment by chrissmiller** [comment]
Thanks @cgillum ! We were trying to use the method I linked in order to use a LastUpdatedTime filter. Our concern with purging based on creation time is that eternal orchestrations with a static instance ID would have a creation time that might be quite old, but would still be actively running. Is this a concern, or will ContinueAsNew update the creation time for the instance?

**Comment by cgillum** [comment]
Regarding eternal orchestrations, are you intending to purge them while they’re still in a Running status? If so, that would be a fairly risky thing to do as it can have unintended side effects. Another option would be to terminate old instances and then use the completion time filter for purging.

**Comment by chrissmiller** [comment]
@cgillum Yeah, that's our concern (problematic interactions with still-running eternal orchestrations with a static instance ID). I just noticed the runtimeStatus args though, so if I understand correctly we can just avoid passing the Running status to that arg and that will prevent it from grabbing the eternal orchestrations?

**Comment by cgillum** [comment]
@chrissmiller yes, the default behavior is to just purge completed instances (those that are Completed, Failed, or Terminated). Excluding the "Running" status from this filter should be safe. It's also a good idea to exclude "Pending" unless you're certain that the pending orchestration will never start.

My suggestion was going to be that you first terminate the orchestration and then use the purge APIs to clean them up.

> will ContinueAsNew update the creation time for the instance?

I did a quick test, and it looks like `ContinueAsNew` does __not__ update the creation time, so yes, the creation time would be quite old. Is this problematic for your use case?

**Comment by chrissmiller** [comment]
Awesome, we will use `PurgeInstanceHistoryAsync` and only include the completed states. Think that covers all our use cases so I'll close the issue -- appreciate your help with this!

**Comment by chrissmiller** [comment]
Ah -- ran into one additional question. TaskHubClient and IOrchestrationServiceClient seem to only expose the interface that isn't implemented here (`PurgeOrchestrationInstanceHistoryAsync`). Do we need to take a direct dependency on our backing storage provider to use the implemented method?

**Comment by cgillum** [comment]
You don't have to take a dependency on them. Instead, take your `IOrchestrationServiceClient` and try to cast it into an `IOrchestrationServicePurgeClient`. We have code that does exactly this to avoid taking a dependency on a specific backend. Something like this:

```csharp
IOrchestrationServiceClient serviceClient = ...
if (serviceClient is IOrchestrationServicePurgeClient purgeClient)
{
    PurgeInstanceFilter purgeInstanceFilter = ...
    return purgeClient.PurgeInstanceStateAsync(purgeInstanceFilter);
}
else
{
    throw new NotSupportedException($"{serviceClient.GetType().Name} doesn't support purge operations.");
}
```

**Comment by chrissmiller** [comment]
Thanks again! Had missed that interface, that covers us. Appreciate all your help here :)
