### ISSUE TITLE
Introduce a new OrchestrationStatus when orchestration is waiting

### ISSUE THREAD

**Issue by hsnsalhi** [Azure/durabletask#801]
Hello,
I want to get a list of orchestration instances that are waiting for human action.
Currently, these instances are in a Running state and we cannot distinguish them from other actually running instances.
Is there a way to do this with existing tools in DTF? if not, is there a chance to introduce a new orchestration status indicating that a given instance is in Waiting status when it is stuck in an "await taskCompletionSource.Task" for example?
Thank you.

**Comment by cgillum** [comment]
Orchestrations have the concept of a "custom status" that you can use for this purpose. To set the custom status, simply override the [`OnGetStatus()`](https://github.com/Azure/durabletask/blob/a0ed8efefb880fda070e274ee170ad68dd53882a/src/DurableTask.Core/TaskOrchestration.cs#L161-L168) method in your orchestration class and return whatever value is appropriate at the time. This value will be returned as part of the `OrchestrationState` that is returned by `TaskHubClient.GetOrchestrationStateAsync()` calls.

**Comment by jviau** [comment]
What @cgillum mentioned is the best option for you. Unfortunately, when an orchestration yields it is opaque to DTFx. The dispatcher does not know what you yielded on at all, only that you did yield. The external event stuff is completely wide open for you to implement, which has its benefits of DTFx not limiting you (too much), but also the downside of the dispatcher cannot infer or do much for you in these scenarios at all - it cannot even detect the difference between a bug (invalid yield that will cause an orphaned orchestration) vs a legitimate wait on external event.

Additionally, even if we do know you are yielding on an external event, it is not limited to an orchestration waiting on _only_ an external event. An orchestration could always wait on `Task.WhenAny(...)` and the provided tasks can be any mix of external event tasks, timers, sub orchestrations, and activities. The dispatcher cannot answer what the orchestration is truly pending on here. Only you, the author, knows the truth of the orchestration state - which is what `OnGetStatus()` is for.
