### ISSUE TITLE
Orchestration stuck in pending state for ServiceBusOrchestrationService after upgrade .Net 6.0

### ISSUE THREAD

**Issue by linsqi** [Azure/durabletask#815]
Seeing orchestration stuck in pending state after upgrade the project to .Net 6.0. The project is based on DurableTask.ServiceBus. From durabletask homepage we also see DurableTask.ServiceBus is no longer actively maintained. Is this a known issue 
 for DurableTask.ServiceBus today?

Also it seems no issue with Net Core 3.1 for DurableTask.ServiceBus. 

For DurableTask.AzureStorage it is working fine after Net 6.0 upgrade.

**Comment by jviau** [comment]
Hi @linsqi, can you provide a minimal repro for us to assist with this issue?

**Comment by linsqi** [comment]
Hi @jviau , thanks for quick reply! I'm able to repro using the [sample project](https://github.com/Azure/durabletask/blob/main/samples/DurableTask.Samples/Program.cs), upgraded to .Net 6.0 and switched to service bus orchestration service. I can only see a record in jumpstart table where the orchestration is in pending state, nothing else. Task hub client is waiting the orchestration until timeout.

**Comment by linsqi** [comment]
Hi @jviau just checking is there any update?

**Comment by jviau** [comment]
@linsqi what version of DurableTask.Core and other packages are you using?

**Comment by jviau** [comment]
@linsqi, this is a bug in the `Microsoft.Azure.ServiceBus` package. You can pin to a fixed version in your project by adding `<PackageVersion Include="Microsoft.Azure.ServiceBus" Version="4.2.1" />` to your project. I have verified that fixes the issue. There are even newer versions, like `5.2.0` - but I am hesitant to recommend a major version bump without further validation.

**Comment by linsqi** [comment]
@jviau Thanks for the quick fix! Verified after service bus pakcage upgraded. We are using Microsoft.Azure.DurableTask.ServiceBus 2.3.0 and Microsoft.Azure.DurableTask.Core 2.3.0 in our services, so keep the same version in the test sample project. Will need to upgrade the package when ready.
