### ISSUE TITLE
Changes in the version 2.12.0 break DurableTask.AzureServiceFabric

### ISSUE THREAD

**Issue by dsempi** [Azure/durabletask#819]
If upgrading to the latest DurableTask.Core (2.12.0) when using DurableTask.AzureServiceFabric, you get the following error:

```Type 'System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' with data contract name 'ArrayOfKeyValueOfstringstring:http://schemas.microsoft.com/2003/10/Serialization/Arrays' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.'```

The issue is caused by the fact `TaskMessage` now contains `OrchestrationExecutionContext` which has a serializable member `IReadOnlyDictionary<string, string> OrchestrationTags` which unfortunately cannot be serialized by the standard `DataContractSerializer` used in Service Fabric environment.

**Comment by jviau** [comment]
Thank you for pointing this out. We did not intend this to be a breaking change and will address it soon. For the time being, are you able to use the previous version of the core library?

**Comment by dsempi** [comment]
Yes, it works fine with 2.11.1. Thanks!

**Comment by RamjotSingh** [comment]
This is fixed in https://github.com/Azure/durabletask/pull/821
