### ISSUE TITLE
`TaskHubWorker` tries to pull work it has no registered orchestrations / activities for.

### ISSUE THREAD

**Issue by ckpearson** [Azure/durabletask#829]
We're currently using durable task (SQL backend) for building out a document production system, as part of that we invoke external software that due to licensing reasons means we have to scope execution to particular hosts.

When spinning up a couple worker applications where one has the orchestration registered and the other does not, the one that doesn't throws an exception presumably because it sees the work item, but cannot find an orchestration to handle it.

Is there a way to configure a worker to only process items it knows how to? Or is there a way I can filter work in the middleware pipeline?

I know we could have a separate task hub to achieve this, but things start getting tricky around dependency injection and making sure things are issued against the correct hub/s - as well as no longer being able to spawn the orchestration as a sub-orchestration across hubs.

Appreciate we could also possibly register a dummy orchestration on the hosts that can't handle it that throw an exception and just have durable task retry that work until we hit a host that can, but that feels like a huge hack.

**Comment by cgillum** [comment]
There's unfortunately no way to configure a worker to only process items it knows how to. All workers therefore must be configured with the same set of activities and orchestrations.

For work that needs to be executed on specific hosts, would it make sense to use an HTTP API that gets called from an activity rather than using an activity directly?

**Comment by ckpearson** [comment]
No worries, We'd come to a similar conclusion and so will likely be looking to either call a web service or stick some work on a storage queue / in a db table and have something pick it up.
