### ISSUE TITLE
Input Output Encryption

### ISSUE THREAD

**Issue by michaelshikh07** [Azure/durabletask#832]
Hi 
Following a previous question 
https://github.com/Azure/durabletask/issues/697

We would like to pass secrets connection strings as an input\ output to an Orchestration\ Activity.
Since it passed as an Orchestration input, I can't use the "get and use" approach within the same activity.
Consider a case a secret is given in request by the user.

The secret value should be encrypted at the input stage and decrypted when Orchestration is running.
We want to avoid encrypting the entire input and encrypt only values marked with a special tag.  

What is the optimal way to implement this? 
Can it be achieved using a custom middleware in charge of encryption\ decryption

@saguiitay FYI

**Comment by saguiitay** [comment]
We ended up implementation a JsonConverter that encrypts/decrypt secrets (based on Attributes).
This allows us to mark certain properties of the input/output of orchestrations and activities with the relevant Attribute, and have the `JsonDataConverter` (which contains a custom `DefaultContractResolver` implementation which uses a custom `IValueProvider` implementation) encrypt/decrypt as needed.

@michaelshikh07 can you close the issue?
