### ISSUE TITLE
How does `ContinueAsNew()` handle the lifetime of the object instance of orchestration

### ISSUE THREAD

**Issue by jundayin** [Azure/durabletask#852]
Hi,

I don't see this is address clearly in the wiki (appreciate if there is indeed a documentation about this). How does the interface `ContinueAsNew()` handle the lifetime of the instance of the orchestration. Does DTF Core dispose the current instance of the orchestration and create a new one to process the new execution (all injected dependencies will be re-instantiated)

**Comment by sebastianburckhardt** [comment]
Yes, `ContinueAsNew` replaces the previous execution instance with a new execution instance. After that, the history of the previous instance is no longer stored, and the instance state is now referring to the new execution.

You can tell which execution an instance state or instance history belongs to by inspecting the `InstanceId` and `ExecutionId` properties. Both the old and the new executions have the same `InstanceId`. But they have different `ExecutionId`.
