### ISSUE TITLE
Stuck orchestration due to ownership lease not being released in certain scenarios shutdown

### ISSUE THREAD

**Issue by cgillum** [Azure/durabletask#860]
This is an ongoing issue for the Azure Storage provider where sometimes a worker instance releases its intent lease but never releases its ownership lease. The result is that orchestrations for that partition get stuck indefinitely, sometimes even for days if not noticed.

The workaround is to restart the app when this happens. However, the problem can be difficult to accurately detect.

One possible way to avoid this is to disable the "safe" partition management strategy. However, disabling this could lead to other issues, such as duplicate executions or split-brain when leases are moved from one worker to another.

/cc @amdeel @davidmrdavid

**Comment by davidmrdavid** [comment]
Resolved in: https://github.com/Azure/durabletask/pull/876
