### ISSUE TITLE
Guidance on writing unit tests & OrchestrationContext

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/durabletask#866]
What is the guidance for writing unit tests & OrchestrationContext? From what I'm seeing there are some fakes but they are internal.

PS: We are on 1.x but curious about approach in 2.x if any.

**Comment by cgillum** [comment]
The recommended strategy is to manually instantiate your `TaskOrchestration` classes and call the appropriate run methods with a mocked `OrchestrationContext`. I recommend the [Moq](https://github.com/moq/moq) framework for doing the mocking.

It would look somewhat similar to what we did in this [Dapr Workflow unit testing example](https://github.com/dapr/dotnet-sdk/blob/master/examples/Workflow/WorkflowUnitTest/OrderProcessingTests.cs), where the SDK is design very similarly to vanilla Durable Task Framework.

**Comment by tomkerkhove** [comment]
We are using Moq indeed and now I'm seeing a way, honestly I forgot what the reason was for asking this as it should simply work - Sorry about that.
