### ISSUE TITLE
Cannot get state for specific executionId

### ISSUE THREAD

**Issue by JalonFlems** [Azure/durabletask#869]
Hello, reaching out for help

When trying to use the `Task<OrchestrationState> GetOrchestrationStateAsync(string instanceId, string executionId)` on an eternal orchestration, I do not receive the orchestrationstate with the correct executionId. It seems that what is returned is the latest execution for the orchestration and I would like to verify if this is unexpected behavior or not.

It would be great to understand if it is possible to query for a specific executionId of an orchestration or if that is not tracked. 

In addition, I noticed that when trying to get the history for any executions besides the latests, the history would return to be empty. Is the history for previous executions saved?

Any help and advice is appreciated, Thanks!

**Comment by JalonFlems** [comment]
We are implementing IOrchestrationServiceClient.

How can we maintain all the execution history for a eternal orchestration?

**Comment by cgillum** [comment]
Are you also implementing `IOrchestrationService`? If so, I expect you should be able to do this by using the execution ID as part of the key that you use when storing your state as part of the `IOrchestrationService.CompleteTaskOrchestrationWorkItemAsync()` method. I think you should be able to get the new execution ID from `OrchestrationRuntimeState.OrchestrationInstance.ExecutionId`.

**Comment by JalonFlems** [comment]
No we're only implementing `IOrchestrationServiceClient` and not `IOrchestrationService`.

My two concerns are: 
1) Can we get an OrchestrationInstance with a specific ExecutionId by implementing `IOrchestrationServiceClient`?
2) Using just this implementation `IOrchestrationServiceClient` will the history for an orchestration be reset once we call `continue-as-new`?

I am relying on the execution history for all previous executions of an orchestration to exist so that I can debug issues for that orchestration.

Please let me know about the behavior of this kind of interface and if there is any way I can configure it, thanks!

**Comment by cgillum** [comment]
1. Whether you can do this depends on how the orchestration state is stored in the task hub, which is dependent on the implementation of `IOrchestrationService`. If that implementation stores each execution ID separately, then yes in theory you could write a `IOrchestrationServiceClient` that fetches orchestration state for specific execution IDs.

3. I don't understand the question - the implementation of `IOrchestrationServiceClient` is unrelated to how orchestration state is managed at runtime or how continue-as-new works.

Assuming that the `IOrchestrationService` implementation you're relying on doesn't keep a history of old execution IDs, you may need to rely on [logging and tracing](https://github.com/Azure/durabletask/tree/main/src/DurableTask.Core/Logging#readme) to debug issues for orchestrations that use continue-as-new.

**Comment by JalonFlems** [comment]
I misunderstood your question before we are using a `AzureStorageOrchestrationService` and you mentioned that it doesn't support getting the state for anything but the latest execution. Can we configure this behavior? If not, what are some work arounds you suggest. Thanks!

**Comment by cgillum** [comment]
It’s not configurable. The only workaround I can suggest is to rely on logging.
