### ISSUE TITLE
Better support for Dependency injection; no notification when the ObjectCreator is done with an instantiated class.

### ISSUE THREAD

**Issue by albertherd** [Azure/durabletask#881]
### Description 

We are currently evaluating whether the DTFx platform is the right platform to host our task / workflow tools that we're building out. We're pleased with most of the platform, but we're stuck on one area - Object Creation.

We're hosting DTFx in a hosted service in .Net. We're also using Dependency injection and EntityFramework. The headache is that the ObjectCreator, out of the box just calls Activator.CreateInstance. Thankfully, the FW provides a way how to override this behaviour, and we're doing that. Essentially something like this => https://andrewstevens.dev/posts/dependency-injection-durable-task/. Which makes sense.

Here's where it gets a bit more complex. We want to ensure that since we're using EntityFramework, we need to create a ServiceScope per "request", which in this case would be processing of an activity. Therefore we need some mechanism so that when an Activity is created, we create a new scope and when the activity is done, we dispose.

The framework does expose the creation, through the Create method within ObjectCreator. The problem is that the FW does not signal in any way when the FW is done from the instantiated Task (and does not honour IDisposable it seems).

Is there some better way of doing things, or maybe I'm just asking something that is impossible within the FW right now?

### Known impact

None

### Expected Behaviour

- ObjectCreator sends a notification when an Activity has successfully completed. This will then be consumed by some DI framework to be able to release. 
- The FW will call Dispose on Activities if the class implements IDisposable

### Actual Behaviour
- There is no capability for the ObjectCreator to notify that it is done from using the object.
- The FW does not call dispose on Actitivies if they implement IDisposable

### Workarounds
None

**Comment by cgillum** [comment]
I think allowing activities to implement `IDisposable` might be the simplest path forward. One worry I have, however, is that existing activity code that already implements `IDisposable` could suddenly start seeing unexpected behavior. A cleaner fix might be to support an object creator that gets the "done" notification, as you suggested. We may need some new interfaces to be able to support this in a non-breaking way.

I don't know if the current set of maintainers will have bandwidth to design and implement this, but we're always happy to accept well-written PRs.

FYI @jviau in case this is something you've encountered before.

**Comment by jviau** [comment]
Hi @albertherd - if you want, I have a DI/hosting library available: https://github.com/jviau/durabletask-hosting. This library handles creating a service scope per orchestration / activity. The solution if you are wondering, is to use middleware and dispose your scope there.

**Comment by jviau** [comment]
Closing as stale
