### ISSUE TITLE
Maybe CommitOutboundQueueMessages should fail-fast when shutdown happens in Azure Stroage provider? 

### ISSUE THREAD

**Issue by jjshao-ms** [Azure/durabletask#885]
Using Azure Storage provider.
I am encountering a host shutdown during my orchestration is running `CommitOutboundQueueMessages` (to be clean, the shutdown is caused by our code, but the framework). I notice that even if the ownership lease has been released due to shutdown, the framework is still enqueueing message to the work item queue. It's ok since I know activity might be executed more than one time, but it would be better if we could reduce the number of duplicate executions.

I didn't see a `CancellationToken` in the following code, maybe that is why it still enqueueing the messages?
https://github.com/Azure/durabletask/blob/53091265df19f18346b94465cc9ef95ffe8f4248/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs#L1251-L1253

**Comment by cgillum** [comment]
> I notice that even if the ownership lease has been released due to shutdown, the framework is still enqueueing message to the work item queue.

This is normal. Even though we released the lease, we still want to finish any in-flight work that we've already started. Releasing the lease is only supposed to stop us from dequeueing new messages from that partition.

I wonder if the problem you're running into is that you're scheduling a huge number of parallel tasks in a single step of the orchestration? It's hard to know when a good time to abort this would be. Aborting could still result in duplicate executions. However, if we finish in time before the process goes down, then we don't have to worry about duplicates. I'm not sure if there's  a clean solution to this problem.

**Comment by jjshao-ms** [comment]
> I wonder if the problem you're running into is that you're scheduling a huge number of parallel tasks in a single step of the orchestration?
Yes, you are right. And we have mitigated this issue by adding fake timers to divide the number in single steps down.
Allow fail-fast will reduce duplicate number for extreme large steps, but without fast-fail will give it a bit more time to complete the execution for small steps. Thanks for your explaining.
