### ISSUE TITLE
Eternal Task Exceptions

### ISSUE THREAD

**Issue by cliedeman** [Azure/durabletask#897]
I have a eternal task (mostly for the singleton pattern)

If there any reason not to do the following in my orchestrate function?

```csharp
       try {
           ... normal orchestraion code
        }
        catch
        {
            var nextRun = context.CurrentUtcDateTime.AddMinutes(5);
            await context.CreateTimer(nextRun, CancellationToken.None);
            context.ContinueAsNew();
            throw;
        }
```

The idea being that being even if this orchestration fails I want it to not end up in the failed state and still perform the next run?

(The reason for the throw is for the my function middle to do the error reporting as per normal)

Thanks
Ciaran

**Comment by amdeel** [comment]
Hey @cliedeman there isn't an issue with using ContinueAsNew in a catch block. However, the orchestrator will complete and start again after the ContinueAsNew and I wouldn't expect the exception to be thrown.

**Comment by cliedeman** [comment]
Thans for the reply @amdeel 

I ended up using this code to ensure the eternal orchestrator never stops

```csharp
finally
        {
            var nextRun = context.CurrentUtcDateTime.AddMinutes(5);
            await context.CreateTimer(nextRun, cancellationToken);
            context.ContinueAsNew();
        }
```

The problem is that if the exception never escape the orchestrator how can I log it? Becaue the exception would bubble up to my exception handler middleware. 
I guess the correct solution is to create a task that logs the exception because if I log the exception directly (sentry http call) because otherwise will be breaking the no io rule. I didn't want to create a task to do this because serializing exceptions will b a pain

**Comment by davidmrdavid** [comment]
@cliedeman: The I/O rule is a bit flexible with respect to logging as far as I'm aware. In general, so long as you're not reading from the environment, you should be able to log your exception. In Durable Functions, for example, we provide a replay safe logger [API](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.durablecontextextensions.createreplaysafelogger?view=azure-dotnet).
