### ISSUE TITLE
Grpc.Net.Client : "Received message exceeds the maximum configured message size."

### ISSUE THREAD

**Issue by sengiv** [Azure/durabletask#908]
When orchestration `output ` exceeds ~3MB "**message exceeds...**" exception is thrown.
**Is there a way to change the limit?**

Current hack to make work:
![image](https://github.com/Azure/durabletask/assets/43817262/8dbb6080-df4a-48c3-bdef-a89aa4a5664e)
I'm sure there is a better way to do this.

_Running on Azure Functions .NET 7_

**Comment by cgillum** [comment]
@sengiv this repo doesn't use `Grpc.Net.Client`. Did you possibly mean to open this issue in another repo, like https://github.com/microsoft/durabletask-dotnet?

**Comment by sengiv** [comment]
oops wrong repo, thanks
