### ISSUE TITLE
How can I terminate the Workflow with a 'Failed' status without throwing an exception?

### ISSUE THREAD

**Issue by goneneren** [Azure/durabletask#920]
I would like to programmatically **end the workflow execution** with a `Failed` status and set a custom output. 

I don't see any methods or properties that I can use in `OrchestrationContext`

I could not find any info in project wiki: https://github.com/Azure/durabletask/wiki/Error-Handling-&-Compensation

Thanks in advance for your help 🙏

**Comment by cgillum** [comment]
There’s currently no way to transition an orchestration to a Failed status except by throwing an unhandled exception.

**Comment by goneneren** [comment]
Thanks @cgillum for the quick answer.

As a quick fix I am throwing an exception serializing the output as the error message. 

```csharp
string json = JsonConvert.SerializeObject(workflowOutput, Formatting.Indented);
throw new Exception(json);
```
